/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ConsensusService.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ConsensusService.pb-c.h"
static const ProtobufCMethodDescriptor proto__consensus_service__method_descriptors[5] =
{
  { "createTopic", &proto__transaction__descriptor, &proto__transaction_response__descriptor },
  { "updateTopic", &proto__transaction__descriptor, &proto__transaction_response__descriptor },
  { "deleteTopic", &proto__transaction__descriptor, &proto__transaction_response__descriptor },
  { "getTopicInfo", &proto__query__descriptor, &proto__response__descriptor },
  { "submitMessage", &proto__transaction__descriptor, &proto__transaction_response__descriptor },
};
const unsigned proto__consensus_service__method_indices_by_name[] = {
  0,        /* createTopic */
  2,        /* deleteTopic */
  3,        /* getTopicInfo */
  4,        /* submitMessage */
  1         /* updateTopic */
};
const ProtobufCServiceDescriptor proto__consensus_service__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "proto.ConsensusService",
  "ConsensusService",
  "Proto__ConsensusService",
  "proto",
  5,
  proto__consensus_service__method_descriptors,
  proto__consensus_service__method_indices_by_name
};
void proto__consensus_service__create_topic(ProtobufCService *service,
                                            const Proto__Transaction *input,
                                            Proto__TransactionResponse_Closure closure,
                                            void *closure_data)
{
  assert(service->descriptor == &proto__consensus_service__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void proto__consensus_service__update_topic(ProtobufCService *service,
                                            const Proto__Transaction *input,
                                            Proto__TransactionResponse_Closure closure,
                                            void *closure_data)
{
  assert(service->descriptor == &proto__consensus_service__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void proto__consensus_service__delete_topic(ProtobufCService *service,
                                            const Proto__Transaction *input,
                                            Proto__TransactionResponse_Closure closure,
                                            void *closure_data)
{
  assert(service->descriptor == &proto__consensus_service__descriptor);
  service->invoke(service, 2, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void proto__consensus_service__get_topic_info(ProtobufCService *service,
                                              const Proto__Query *input,
                                              Proto__Response_Closure closure,
                                              void *closure_data)
{
  assert(service->descriptor == &proto__consensus_service__descriptor);
  service->invoke(service, 3, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void proto__consensus_service__submit_message(ProtobufCService *service,
                                              const Proto__Transaction *input,
                                              Proto__TransactionResponse_Closure closure,
                                              void *closure_data)
{
  assert(service->descriptor == &proto__consensus_service__descriptor);
  service->invoke(service, 4, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void proto__consensus_service__init (Proto__ConsensusService_Service *service,
                                     Proto__ConsensusService_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &proto__consensus_service__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
