/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ConsensusDeleteTopic.proto */

#ifndef PROTOBUF_C_ConsensusDeleteTopic_2eproto__INCLUDED
#define PROTOBUF_C_ConsensusDeleteTopic_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "BasicTypes.pb-c.h"

typedef struct Proto__ConsensusDeleteTopicTransactionBody Proto__ConsensusDeleteTopicTransactionBody;


/* --- enums --- */


/* --- messages --- */

/*
 * See [ConsensusService.deleteTopic()](#proto.ConsensusService)
 */
struct  Proto__ConsensusDeleteTopicTransactionBody
{
  ProtobufCMessage base;
  /*
   * Topic identifier.
   */
  Proto__TopicID *topicid;
};
#define PROTO__CONSENSUS_DELETE_TOPIC_TRANSACTION_BODY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__consensus_delete_topic_transaction_body__descriptor) \
    , NULL }


/* Proto__ConsensusDeleteTopicTransactionBody methods */
void   proto__consensus_delete_topic_transaction_body__init
                     (Proto__ConsensusDeleteTopicTransactionBody         *message);
size_t proto__consensus_delete_topic_transaction_body__get_packed_size
                     (const Proto__ConsensusDeleteTopicTransactionBody   *message);
size_t proto__consensus_delete_topic_transaction_body__pack
                     (const Proto__ConsensusDeleteTopicTransactionBody   *message,
                      uint8_t             *out);
size_t proto__consensus_delete_topic_transaction_body__pack_to_buffer
                     (const Proto__ConsensusDeleteTopicTransactionBody   *message,
                      ProtobufCBuffer     *buffer);
Proto__ConsensusDeleteTopicTransactionBody *
       proto__consensus_delete_topic_transaction_body__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__consensus_delete_topic_transaction_body__free_unpacked
                     (Proto__ConsensusDeleteTopicTransactionBody *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Proto__ConsensusDeleteTopicTransactionBody_Closure)
                 (const Proto__ConsensusDeleteTopicTransactionBody *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor proto__consensus_delete_topic_transaction_body__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_ConsensusDeleteTopic_2eproto__INCLUDED */
