/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ConsensusTopicInfo.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ConsensusTopicInfo.pb-c.h"
void   proto__consensus_topic_info__init
                     (Proto__ConsensusTopicInfo         *message)
{
  static const Proto__ConsensusTopicInfo init_value = PROTO__CONSENSUS_TOPIC_INFO__INIT;
  *message = init_value;
}
size_t proto__consensus_topic_info__get_packed_size
                     (const Proto__ConsensusTopicInfo *message)
{
  assert(message->base.descriptor == &proto__consensus_topic_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__consensus_topic_info__pack
                     (const Proto__ConsensusTopicInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__consensus_topic_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__consensus_topic_info__pack_to_buffer
                     (const Proto__ConsensusTopicInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__consensus_topic_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__ConsensusTopicInfo *
       proto__consensus_topic_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__ConsensusTopicInfo *)
     protobuf_c_message_unpack (&proto__consensus_topic_info__descriptor,
                                allocator, len, data);
}
void   proto__consensus_topic_info__free_unpacked
                     (Proto__ConsensusTopicInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__consensus_topic_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor proto__consensus_topic_info__field_descriptors[8] =
{
  {
    "memo",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Proto__ConsensusTopicInfo, memo),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "runningHash",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Proto__ConsensusTopicInfo, runninghash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sequenceNumber",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Proto__ConsensusTopicInfo, sequencenumber),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "expirationTime",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__ConsensusTopicInfo, expirationtime),
    &proto__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "adminKey",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__ConsensusTopicInfo, adminkey),
    &proto__key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "submitKey",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__ConsensusTopicInfo, submitkey),
    &proto__key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "autoRenewPeriod",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__ConsensusTopicInfo, autorenewperiod),
    &proto__duration__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "autoRenewAccount",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__ConsensusTopicInfo, autorenewaccount),
    &proto__account_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__consensus_topic_info__field_indices_by_name[] = {
  4,   /* field[4] = adminKey */
  7,   /* field[7] = autoRenewAccount */
  6,   /* field[6] = autoRenewPeriod */
  3,   /* field[3] = expirationTime */
  0,   /* field[0] = memo */
  1,   /* field[1] = runningHash */
  2,   /* field[2] = sequenceNumber */
  5,   /* field[5] = submitKey */
};
static const ProtobufCIntRange proto__consensus_topic_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor proto__consensus_topic_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.ConsensusTopicInfo",
  "ConsensusTopicInfo",
  "Proto__ConsensusTopicInfo",
  "proto",
  sizeof(Proto__ConsensusTopicInfo),
  8,
  proto__consensus_topic_info__field_descriptors,
  proto__consensus_topic_info__field_indices_by_name,
  1,  proto__consensus_topic_info__number_ranges,
  (ProtobufCMessageInit) proto__consensus_topic_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
