/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: CustomFees.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "CustomFees.pb-c.h"
void   proto__fractional_fee__init
                     (Proto__FractionalFee         *message)
{
  static const Proto__FractionalFee init_value = PROTO__FRACTIONAL_FEE__INIT;
  *message = init_value;
}
size_t proto__fractional_fee__get_packed_size
                     (const Proto__FractionalFee *message)
{
  assert(message->base.descriptor == &proto__fractional_fee__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__fractional_fee__pack
                     (const Proto__FractionalFee *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__fractional_fee__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__fractional_fee__pack_to_buffer
                     (const Proto__FractionalFee *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__fractional_fee__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__FractionalFee *
       proto__fractional_fee__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__FractionalFee *)
     protobuf_c_message_unpack (&proto__fractional_fee__descriptor,
                                allocator, len, data);
}
void   proto__fractional_fee__free_unpacked
                     (Proto__FractionalFee *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__fractional_fee__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__fixed_fee__init
                     (Proto__FixedFee         *message)
{
  static const Proto__FixedFee init_value = PROTO__FIXED_FEE__INIT;
  *message = init_value;
}
size_t proto__fixed_fee__get_packed_size
                     (const Proto__FixedFee *message)
{
  assert(message->base.descriptor == &proto__fixed_fee__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__fixed_fee__pack
                     (const Proto__FixedFee *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__fixed_fee__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__fixed_fee__pack_to_buffer
                     (const Proto__FixedFee *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__fixed_fee__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__FixedFee *
       proto__fixed_fee__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__FixedFee *)
     protobuf_c_message_unpack (&proto__fixed_fee__descriptor,
                                allocator, len, data);
}
void   proto__fixed_fee__free_unpacked
                     (Proto__FixedFee *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__fixed_fee__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__custom_fee__init
                     (Proto__CustomFee         *message)
{
  static const Proto__CustomFee init_value = PROTO__CUSTOM_FEE__INIT;
  *message = init_value;
}
size_t proto__custom_fee__get_packed_size
                     (const Proto__CustomFee *message)
{
  assert(message->base.descriptor == &proto__custom_fee__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__custom_fee__pack
                     (const Proto__CustomFee *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__custom_fee__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__custom_fee__pack_to_buffer
                     (const Proto__CustomFee *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__custom_fee__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__CustomFee *
       proto__custom_fee__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__CustomFee *)
     protobuf_c_message_unpack (&proto__custom_fee__descriptor,
                                allocator, len, data);
}
void   proto__custom_fee__free_unpacked
                     (Proto__CustomFee *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__custom_fee__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__assessed_custom_fee__init
                     (Proto__AssessedCustomFee         *message)
{
  static const Proto__AssessedCustomFee init_value = PROTO__ASSESSED_CUSTOM_FEE__INIT;
  *message = init_value;
}
size_t proto__assessed_custom_fee__get_packed_size
                     (const Proto__AssessedCustomFee *message)
{
  assert(message->base.descriptor == &proto__assessed_custom_fee__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__assessed_custom_fee__pack
                     (const Proto__AssessedCustomFee *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__assessed_custom_fee__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__assessed_custom_fee__pack_to_buffer
                     (const Proto__AssessedCustomFee *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__assessed_custom_fee__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__AssessedCustomFee *
       proto__assessed_custom_fee__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__AssessedCustomFee *)
     protobuf_c_message_unpack (&proto__assessed_custom_fee__descriptor,
                                allocator, len, data);
}
void   proto__assessed_custom_fee__free_unpacked
                     (Proto__AssessedCustomFee *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__assessed_custom_fee__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor proto__fractional_fee__field_descriptors[3] =
{
  {
    "fractional_amount",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__FractionalFee, fractional_amount),
    &proto__fraction__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "minimum_amount",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Proto__FractionalFee, minimum_amount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maximum_amount",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Proto__FractionalFee, maximum_amount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__fractional_fee__field_indices_by_name[] = {
  0,   /* field[0] = fractional_amount */
  2,   /* field[2] = maximum_amount */
  1,   /* field[1] = minimum_amount */
};
static const ProtobufCIntRange proto__fractional_fee__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor proto__fractional_fee__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.FractionalFee",
  "FractionalFee",
  "Proto__FractionalFee",
  "proto",
  sizeof(Proto__FractionalFee),
  3,
  proto__fractional_fee__field_descriptors,
  proto__fractional_fee__field_indices_by_name,
  1,  proto__fractional_fee__number_ranges,
  (ProtobufCMessageInit) proto__fractional_fee__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__fixed_fee__field_descriptors[2] =
{
  {
    "amount",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Proto__FixedFee, amount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "denominating_token_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__FixedFee, denominating_token_id),
    &proto__token_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__fixed_fee__field_indices_by_name[] = {
  0,   /* field[0] = amount */
  1,   /* field[1] = denominating_token_id */
};
static const ProtobufCIntRange proto__fixed_fee__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto__fixed_fee__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.FixedFee",
  "FixedFee",
  "Proto__FixedFee",
  "proto",
  sizeof(Proto__FixedFee),
  2,
  proto__fixed_fee__field_descriptors,
  proto__fixed_fee__field_indices_by_name,
  1,  proto__fixed_fee__number_ranges,
  (ProtobufCMessageInit) proto__fixed_fee__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__custom_fee__field_descriptors[3] =
{
  {
    "fixed_fee",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Proto__CustomFee, fee_case),
    offsetof(Proto__CustomFee, fixed_fee),
    &proto__fixed_fee__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fractional_fee",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Proto__CustomFee, fee_case),
    offsetof(Proto__CustomFee, fractional_fee),
    &proto__fractional_fee__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fee_collector_account_id",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__CustomFee, fee_collector_account_id),
    &proto__account_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__custom_fee__field_indices_by_name[] = {
  2,   /* field[2] = fee_collector_account_id */
  0,   /* field[0] = fixed_fee */
  1,   /* field[1] = fractional_fee */
};
static const ProtobufCIntRange proto__custom_fee__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor proto__custom_fee__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.CustomFee",
  "CustomFee",
  "Proto__CustomFee",
  "proto",
  sizeof(Proto__CustomFee),
  3,
  proto__custom_fee__field_descriptors,
  proto__custom_fee__field_indices_by_name,
  1,  proto__custom_fee__number_ranges,
  (ProtobufCMessageInit) proto__custom_fee__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__assessed_custom_fee__field_descriptors[3] =
{
  {
    "amount",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Proto__AssessedCustomFee, amount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "token_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__AssessedCustomFee, token_id),
    &proto__token_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fee_collector_account_id",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__AssessedCustomFee, fee_collector_account_id),
    &proto__account_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__assessed_custom_fee__field_indices_by_name[] = {
  0,   /* field[0] = amount */
  2,   /* field[2] = fee_collector_account_id */
  1,   /* field[1] = token_id */
};
static const ProtobufCIntRange proto__assessed_custom_fee__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor proto__assessed_custom_fee__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.AssessedCustomFee",
  "AssessedCustomFee",
  "Proto__AssessedCustomFee",
  "proto",
  sizeof(Proto__AssessedCustomFee),
  3,
  proto__assessed_custom_fee__field_descriptors,
  proto__assessed_custom_fee__field_indices_by_name,
  1,  proto__assessed_custom_fee__number_ranges,
  (ProtobufCMessageInit) proto__assessed_custom_fee__init,
  NULL,NULL,NULL    /* reserved[123] */
};
