/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Freeze.proto */

#ifndef PROTOBUF_C_Freeze_2eproto__INCLUDED
#define PROTOBUF_C_Freeze_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "Duration.pb-c.h"
#include "Timestamp.pb-c.h"
#include "BasicTypes.pb-c.h"

typedef struct Proto__FreezeTransactionBody Proto__FreezeTransactionBody;


/* --- enums --- */


/* --- messages --- */

/*
 * Set the freezing period in which the platform will stop creating events and accepting transactions. This is used before safely shut down the platform for maintenance. 
 */
struct  Proto__FreezeTransactionBody
{
  ProtobufCMessage base;
  /*
   * The start hour (in UTC time), a value between 0 and 23
   */
  int32_t starthour;
  /*
   * The start minute (in UTC time), a value between 0 and 59
   */
  int32_t startmin;
  /*
   * The end hour (in UTC time), a value between 0 and 23
   */
  int32_t endhour;
  /*
   * The end minute (in UTC time), a value between 0 and 59
   */
  int32_t endmin;
  /*
   * The ID of the file needs to be updated during a freeze transaction
   */
  Proto__FileID *updatefile;
  /*
   * The hash value of the file, used to verify file content before performing freeze and update
   */
  ProtobufCBinaryData filehash;
};
#define PROTO__FREEZE_TRANSACTION_BODY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__freeze_transaction_body__descriptor) \
    , 0, 0, 0, 0, NULL, {0,NULL} }


/* Proto__FreezeTransactionBody methods */
void   proto__freeze_transaction_body__init
                     (Proto__FreezeTransactionBody         *message);
size_t proto__freeze_transaction_body__get_packed_size
                     (const Proto__FreezeTransactionBody   *message);
size_t proto__freeze_transaction_body__pack
                     (const Proto__FreezeTransactionBody   *message,
                      uint8_t             *out);
size_t proto__freeze_transaction_body__pack_to_buffer
                     (const Proto__FreezeTransactionBody   *message,
                      ProtobufCBuffer     *buffer);
Proto__FreezeTransactionBody *
       proto__freeze_transaction_body__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__freeze_transaction_body__free_unpacked
                     (Proto__FreezeTransactionBody *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Proto__FreezeTransactionBody_Closure)
                 (const Proto__FreezeTransactionBody *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor proto__freeze_transaction_body__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_Freeze_2eproto__INCLUDED */
