/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: NetworkService.proto */

#ifndef PROTOBUF_C_NetworkService_2eproto__INCLUDED
#define PROTOBUF_C_NetworkService_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "Query.pb-c.h"
#include "Response.pb-c.h"
#include "TransactionResponse.pb-c.h"
#include "Transaction.pb-c.h"



/* --- enums --- */


/* --- messages --- */

/* --- per-message closures --- */


/* --- services --- */

typedef struct Proto__NetworkService_Service Proto__NetworkService_Service;
struct Proto__NetworkService_Service
{
  ProtobufCService base;
  void (*get_version_info)(Proto__NetworkService_Service *service,
                           const Proto__Query *input,
                           Proto__Response_Closure closure,
                           void *closure_data);
  void (*unchecked_submit)(Proto__NetworkService_Service *service,
                           const Proto__Transaction *input,
                           Proto__TransactionResponse_Closure closure,
                           void *closure_data);
};
typedef void (*Proto__NetworkService_ServiceDestroy)(Proto__NetworkService_Service *);
void proto__network_service__init (Proto__NetworkService_Service *service,
                                   Proto__NetworkService_ServiceDestroy destroy);
#define PROTO__NETWORK_SERVICE__BASE_INIT \
    { &proto__network_service__descriptor, protobuf_c_service_invoke_internal, NULL }
#define PROTO__NETWORK_SERVICE__INIT(function_prefix__) \
    { PROTO__NETWORK_SERVICE__BASE_INIT,\
      function_prefix__ ## get_version_info,\
      function_prefix__ ## unchecked_submit  }
void proto__network_service__get_version_info(ProtobufCService *service,
                                              const Proto__Query *input,
                                              Proto__Response_Closure closure,
                                              void *closure_data);
void proto__network_service__unchecked_submit(ProtobufCService *service,
                                              const Proto__Transaction *input,
                                              Proto__TransactionResponse_Closure closure,
                                              void *closure_data);

/* --- descriptors --- */

extern const ProtobufCServiceDescriptor proto__network_service__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_NetworkService_2eproto__INCLUDED */
