/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ResponseCode.proto */

#ifndef PROTOBUF_C_ResponseCode_2eproto__INCLUDED
#define PROTOBUF_C_ResponseCode_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif




/* --- enums --- */

typedef enum _Proto__ResponseCodeEnum {
  /*
   * The transaction passed the precheck validations.
   */
  PROTO__RESPONSE_CODE_ENUM__OK = 0,
  /*
   * For any error not handled by specific error codes listed below.
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_TRANSACTION = 1,
  /*
   *Payer account does not exist.
   */
  PROTO__RESPONSE_CODE_ENUM__PAYER_ACCOUNT_NOT_FOUND = 2,
  /*
   *Node Account provided does not match the node account of the node the transaction was submitted to.
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_NODE_ACCOUNT = 3,
  /*
   * Pre-Check error when TransactionValidStart + transactionValidDuration is less than current consensus time.
   */
  PROTO__RESPONSE_CODE_ENUM__TRANSACTION_EXPIRED = 4,
  /*
   * Transaction start time is greater than current consensus time
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_TRANSACTION_START = 5,
  /*
   *valid transaction duration is a positive non zero number that does not exceed 120 seconds
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_TRANSACTION_DURATION = 6,
  /*
   * The transaction signature is not valid
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_SIGNATURE = 7,
  /*
   *Transaction memo size exceeded 100 bytes
   */
  PROTO__RESPONSE_CODE_ENUM__MEMO_TOO_LONG = 8,
  /*
   * The fee provided in the transaction is insufficient for this type of transaction
   */
  PROTO__RESPONSE_CODE_ENUM__INSUFFICIENT_TX_FEE = 9,
  /*
   * The payer account has insufficient cryptocurrency to pay the transaction fee
   */
  PROTO__RESPONSE_CODE_ENUM__INSUFFICIENT_PAYER_BALANCE = 10,
  /*
   * This transaction ID is a duplicate of one that was submitted to this node or reached consensus in the last 180 seconds (receipt period)
   */
  PROTO__RESPONSE_CODE_ENUM__DUPLICATE_TRANSACTION = 11,
  /*
   *If API is throttled out
   */
  PROTO__RESPONSE_CODE_ENUM__BUSY = 12,
  /*
   *The API is not currently supported
   */
  PROTO__RESPONSE_CODE_ENUM__NOT_SUPPORTED = 13,
  /*
   *The file id is invalid or does not exist
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_FILE_ID = 14,
  /*
   *The account id is invalid or does not exist
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_ACCOUNT_ID = 15,
  /*
   *The contract id is invalid or does not exist
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_CONTRACT_ID = 16,
  /*
   *Transaction id is not valid
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_TRANSACTION_ID = 17,
  /*
   *Receipt for given transaction id does not exist
   */
  PROTO__RESPONSE_CODE_ENUM__RECEIPT_NOT_FOUND = 18,
  /*
   *Record for given transaction id does not exist
   */
  PROTO__RESPONSE_CODE_ENUM__RECORD_NOT_FOUND = 19,
  /*
   *The solidity id is invalid or entity with this solidity id does not exist
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_SOLIDITY_ID = 20,
  /*
   * The responding node has submitted the transaction to the network. Its final status is still unknown.
   */
  PROTO__RESPONSE_CODE_ENUM__UNKNOWN = 21,
  /*
   * The transaction succeeded
   */
  PROTO__RESPONSE_CODE_ENUM__SUCCESS = 22,
  /*
   * There was a system error and the transaction failed because of invalid request parameters.
   */
  PROTO__RESPONSE_CODE_ENUM__FAIL_INVALID = 23,
  /*
   * There was a system error while performing fee calculation, reserved for future.
   */
  PROTO__RESPONSE_CODE_ENUM__FAIL_FEE = 24,
  /*
   * There was a system error while performing balance checks, reserved for future.
   */
  PROTO__RESPONSE_CODE_ENUM__FAIL_BALANCE = 25,
  /*
   *Key not provided in the transaction body
   */
  PROTO__RESPONSE_CODE_ENUM__KEY_REQUIRED = 26,
  /*
   *Unsupported algorithm/encoding used for keys in the transaction
   */
  PROTO__RESPONSE_CODE_ENUM__BAD_ENCODING = 27,
  /*
   *When the account balance is not sufficient for the transfer
   */
  PROTO__RESPONSE_CODE_ENUM__INSUFFICIENT_ACCOUNT_BALANCE = 28,
  /*
   *During an update transaction when the system is not able to find the Users Solidity address
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_SOLIDITY_ADDRESS = 29,
  /*
   *Not enough gas was supplied to execute transaction
   */
  PROTO__RESPONSE_CODE_ENUM__INSUFFICIENT_GAS = 30,
  /*
   *contract byte code size is over the limit
   */
  PROTO__RESPONSE_CODE_ENUM__CONTRACT_SIZE_LIMIT_EXCEEDED = 31,
  /*
   *local execution (query) is requested for a function which changes state
   */
  PROTO__RESPONSE_CODE_ENUM__LOCAL_CALL_MODIFICATION_EXCEPTION = 32,
  /*
   *Contract REVERT OPCODE executed
   */
  PROTO__RESPONSE_CODE_ENUM__CONTRACT_REVERT_EXECUTED = 33,
  /*
   *For any contract execution related error not handled by specific error codes listed above.
   */
  PROTO__RESPONSE_CODE_ENUM__CONTRACT_EXECUTION_EXCEPTION = 34,
  /*
   *In Query validation, account with +ve(amount) value should be Receiving node account, the receiver account should be only one account in the list
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_RECEIVING_NODE_ACCOUNT = 35,
  /*
   * Header is missing in Query request
   */
  PROTO__RESPONSE_CODE_ENUM__MISSING_QUERY_HEADER = 36,
  /*
   * The update of the account failed
   */
  PROTO__RESPONSE_CODE_ENUM__ACCOUNT_UPDATE_FAILED = 37,
  /*
   * Provided key encoding was not supported by the system
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_KEY_ENCODING = 38,
  /*
   * null solidity address
   */
  PROTO__RESPONSE_CODE_ENUM__NULL_SOLIDITY_ADDRESS = 39,
  /*
   * update of the contract failed
   */
  PROTO__RESPONSE_CODE_ENUM__CONTRACT_UPDATE_FAILED = 40,
  /*
   * the query header is invalid
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_QUERY_HEADER = 41,
  /*
   * Invalid fee submitted
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_FEE_SUBMITTED = 42,
  /*
   * Payer signature is invalid
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_PAYER_SIGNATURE = 43,
  /*
   * The keys were not provided in the request.
   */
  PROTO__RESPONSE_CODE_ENUM__KEY_NOT_PROVIDED = 44,
  /*
   * Expiration time provided in the transaction was invalid.
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_EXPIRATION_TIME = 45,
  /*
   *WriteAccess Control Keys are not provided for the file
   */
  PROTO__RESPONSE_CODE_ENUM__NO_WACL_KEY = 46,
  /*
   *The contents of file are provided as empty.
   */
  PROTO__RESPONSE_CODE_ENUM__FILE_CONTENT_EMPTY = 47,
  /*
   * The crypto transfer credit and debit do not sum equal to 0
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_ACCOUNT_AMOUNTS = 48,
  /*
   * Transaction body provided is empty
   */
  PROTO__RESPONSE_CODE_ENUM__EMPTY_TRANSACTION_BODY = 49,
  /*
   * Invalid transaction body provided
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_TRANSACTION_BODY = 50,
  /*
   * the type of key (base ed25519 key, KeyList, or ThresholdKey) does not match the type of signature (base ed25519 signature, SignatureList, or ThresholdKeySignature)
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_SIGNATURE_TYPE_MISMATCHING_KEY = 51,
  /*
   * the number of key (KeyList, or ThresholdKey) does not match that of signature (SignatureList, or ThresholdKeySignature). e.g. if a keyList has 3 base keys, then the corresponding signatureList should also have 3 base signatures.
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_SIGNATURE_COUNT_MISMATCHING_KEY = 52,
  /*
   * the livehash body is empty
   */
  PROTO__RESPONSE_CODE_ENUM__EMPTY_LIVE_HASH_BODY = 53,
  /*
   * the livehash data is missing
   */
  PROTO__RESPONSE_CODE_ENUM__EMPTY_LIVE_HASH = 54,
  /*
   * the keys for a livehash are missing
   */
  PROTO__RESPONSE_CODE_ENUM__EMPTY_LIVE_HASH_KEYS = 55,
  /*
   * the livehash data is not the output of a SHA-384 digest
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_LIVE_HASH_SIZE = 56,
  /*
   * the query body is empty
   */
  PROTO__RESPONSE_CODE_ENUM__EMPTY_QUERY_BODY = 57,
  /*
   * the crypto livehash query is empty
   */
  PROTO__RESPONSE_CODE_ENUM__EMPTY_LIVE_HASH_QUERY = 58,
  /*
   * the livehash is not present
   */
  PROTO__RESPONSE_CODE_ENUM__LIVE_HASH_NOT_FOUND = 59,
  /*
   * the account id passed has not yet been created.
   */
  PROTO__RESPONSE_CODE_ENUM__ACCOUNT_ID_DOES_NOT_EXIST = 60,
  /*
   * the livehash already exists for a given account
   */
  PROTO__RESPONSE_CODE_ENUM__LIVE_HASH_ALREADY_EXISTS = 61,
  /*
   * File WACL keys are invalid
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_FILE_WACL = 62,
  /*
   * Serialization failure
   */
  PROTO__RESPONSE_CODE_ENUM__SERIALIZATION_FAILED = 63,
  /*
   * The size of the Transaction is greater than transactionMaxBytes
   */
  PROTO__RESPONSE_CODE_ENUM__TRANSACTION_OVERSIZE = 64,
  /*
   * The Transaction has more than 50 levels
   */
  PROTO__RESPONSE_CODE_ENUM__TRANSACTION_TOO_MANY_LAYERS = 65,
  /*
   *Contract is marked as deleted
   */
  PROTO__RESPONSE_CODE_ENUM__CONTRACT_DELETED = 66,
  /*
   * the platform node is either disconnected or lagging behind.
   */
  PROTO__RESPONSE_CODE_ENUM__PLATFORM_NOT_ACTIVE = 67,
  /*
   * one public key matches more than one prefixes on the signature map
   */
  PROTO__RESPONSE_CODE_ENUM__KEY_PREFIX_MISMATCH = 68,
  /*
   * transaction not created by platform due to large backlog
   */
  PROTO__RESPONSE_CODE_ENUM__PLATFORM_TRANSACTION_NOT_CREATED = 69,
  /*
   * auto renewal period is not a positive number of seconds
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_RENEWAL_PERIOD = 70,
  /*
   * the response code when a smart contract id is passed for a crypto API request
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_PAYER_ACCOUNT_ID = 71,
  /*
   * the account has been marked as deleted
   */
  PROTO__RESPONSE_CODE_ENUM__ACCOUNT_DELETED = 72,
  /*
   * the file has been marked as deleted
   */
  PROTO__RESPONSE_CODE_ENUM__FILE_DELETED = 73,
  /*
   * same accounts repeated in the transfer account list
   */
  PROTO__RESPONSE_CODE_ENUM__ACCOUNT_REPEATED_IN_ACCOUNT_AMOUNTS = 74,
  /*
   * attempting to set negative balance value for crypto account
   */
  PROTO__RESPONSE_CODE_ENUM__SETTING_NEGATIVE_ACCOUNT_BALANCE = 75,
  /*
   * when deleting smart contract that has crypto balance either transfer account or transfer smart contract is required
   */
  PROTO__RESPONSE_CODE_ENUM__OBTAINER_REQUIRED = 76,
  /*
   *when deleting smart contract that has crypto balance you can not use the same contract id as transferContractId as the one being deleted
   */
  PROTO__RESPONSE_CODE_ENUM__OBTAINER_SAME_CONTRACT_ID = 77,
  /*
   *transferAccountId or transferContractId specified for contract delete does not exist
   */
  PROTO__RESPONSE_CODE_ENUM__OBTAINER_DOES_NOT_EXIST = 78,
  /*
   *attempting to modify (update or delete a immutable smart contract, i.e. one created without a admin key)
   */
  PROTO__RESPONSE_CODE_ENUM__MODIFYING_IMMUTABLE_CONTRACT = 79,
  /*
   *Unexpected exception thrown by file system functions
   */
  PROTO__RESPONSE_CODE_ENUM__FILE_SYSTEM_EXCEPTION = 80,
  /*
   * the duration is not a subset of [MINIMUM_AUTORENEW_DURATION,MAXIMUM_AUTORENEW_DURATION]
   */
  PROTO__RESPONSE_CODE_ENUM__AUTORENEW_DURATION_NOT_IN_RANGE = 81,
  /*
   * Decoding the smart contract binary to a byte array failed. Check that the input is a valid hex string.
   */
  PROTO__RESPONSE_CODE_ENUM__ERROR_DECODING_BYTESTRING = 82,
  /*
   * File to create a smart contract was of length zero
   */
  PROTO__RESPONSE_CODE_ENUM__CONTRACT_FILE_EMPTY = 83,
  /*
   * Bytecode for smart contract is of length zero
   */
  PROTO__RESPONSE_CODE_ENUM__CONTRACT_BYTECODE_EMPTY = 84,
  /*
   * Attempt to set negative initial balance
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_INITIAL_BALANCE = 85,
  /*
   * [Deprecated]. attempt to set negative receive record threshold
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_RECEIVE_RECORD_THRESHOLD = 86,
  /*
   * [Deprecated]. attempt to set negative send record threshold
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_SEND_RECORD_THRESHOLD = 87,
  /*
   * Special Account Operations should be performed by only Genesis account, return this code if it is not Genesis Account
   */
  PROTO__RESPONSE_CODE_ENUM__ACCOUNT_IS_NOT_GENESIS_ACCOUNT = 88,
  /*
   * The fee payer account doesn't have permission to submit such Transaction
   */
  PROTO__RESPONSE_CODE_ENUM__PAYER_ACCOUNT_UNAUTHORIZED = 89,
  /*
   * FreezeTransactionBody is invalid
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_FREEZE_TRANSACTION_BODY = 90,
  /*
   * FreezeTransactionBody does not exist
   */
  PROTO__RESPONSE_CODE_ENUM__FREEZE_TRANSACTION_BODY_NOT_FOUND = 91,
  /*
   *Exceeded the number of accounts (both from and to) allowed for crypto transfer list
   */
  PROTO__RESPONSE_CODE_ENUM__TRANSFER_LIST_SIZE_LIMIT_EXCEEDED = 92,
  /*
   * Smart contract result size greater than specified maxResultSize
   */
  PROTO__RESPONSE_CODE_ENUM__RESULT_SIZE_LIMIT_EXCEEDED = 93,
  /*
   *The payer account is not a special account(account 0.0.55)
   */
  PROTO__RESPONSE_CODE_ENUM__NOT_SPECIAL_ACCOUNT = 94,
  /*
   * Negative gas was offered in smart contract call
   */
  PROTO__RESPONSE_CODE_ENUM__CONTRACT_NEGATIVE_GAS = 95,
  /*
   * Negative value / initial balance was specified in a smart contract call / create
   */
  PROTO__RESPONSE_CODE_ENUM__CONTRACT_NEGATIVE_VALUE = 96,
  /*
   * Failed to update fee file
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_FEE_FILE = 97,
  /*
   * Failed to update exchange rate file
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_EXCHANGE_RATE_FILE = 98,
  /*
   * Payment tendered for contract local call cannot cover both the fee and the gas
   */
  PROTO__RESPONSE_CODE_ENUM__INSUFFICIENT_LOCAL_CALL_GAS = 99,
  /*
   * Entities with Entity ID below 1000 are not allowed to be deleted
   */
  PROTO__RESPONSE_CODE_ENUM__ENTITY_NOT_ALLOWED_TO_DELETE = 100,
  /*
   * Violating one of these rules: 1) treasury account can update all entities below 0.0.1000, 2) account 0.0.50 can update all entities from 0.0.51 - 0.0.80, 3) Network Function Master Account A/c 0.0.50 - Update all Network Function accounts & perform all the Network Functions listed below, 4) Network Function Accounts: i) A/c 0.0.55 - Update Address Book files (0.0.101/102), ii) A/c 0.0.56 - Update Fee schedule (0.0.111), iii) A/c 0.0.57 - Update Exchange Rate (0.0.112).
   */
  PROTO__RESPONSE_CODE_ENUM__AUTHORIZATION_FAILED = 101,
  /*
   * Fee Schedule Proto uploaded but not valid (append or update is required)
   */
  PROTO__RESPONSE_CODE_ENUM__FILE_UPLOADED_PROTO_INVALID = 102,
  /*
   * Fee Schedule Proto uploaded but not valid (append or update is required)
   */
  PROTO__RESPONSE_CODE_ENUM__FILE_UPLOADED_PROTO_NOT_SAVED_TO_DISK = 103,
  /*
   * Fee Schedule Proto File Part uploaded
   */
  PROTO__RESPONSE_CODE_ENUM__FEE_SCHEDULE_FILE_PART_UPLOADED = 104,
  /*
   * The change on Exchange Rate exceeds Exchange_Rate_Allowed_Percentage
   */
  PROTO__RESPONSE_CODE_ENUM__EXCHANGE_RATE_CHANGE_LIMIT_EXCEEDED = 105,
  /*
   * Contract permanent storage exceeded the currently allowable limit
   */
  PROTO__RESPONSE_CODE_ENUM__MAX_CONTRACT_STORAGE_EXCEEDED = 106,
  /*
   * Transfer Account should not be same as Account to be deleted
   */
  PROTO__RESPONSE_CODE_ENUM__TRANSFER_ACCOUNT_SAME_AS_DELETE_ACCOUNT = 107,
  PROTO__RESPONSE_CODE_ENUM__TOTAL_LEDGER_BALANCE_INVALID = 108,
  /*
   * The expiration date/time on a smart contract may not be reduced
   */
  PROTO__RESPONSE_CODE_ENUM__EXPIRATION_REDUCTION_NOT_ALLOWED = 110,
  /*
   *Gas exceeded currently allowable gas limit per transaction
   */
  PROTO__RESPONSE_CODE_ENUM__MAX_GAS_LIMIT_EXCEEDED = 111,
  /*
   * File size exceeded the currently allowable limit
   */
  PROTO__RESPONSE_CODE_ENUM__MAX_FILE_SIZE_EXCEEDED = 112,
  /*
   * When a valid signature is not provided for operations on account with receiverSigRequired=true
   */
  PROTO__RESPONSE_CODE_ENUM__RECEIVER_SIG_REQUIRED = 113,
  /*
   * The Topic ID specified is not in the system.
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_TOPIC_ID = 150,
  /*
   * A provided admin key was invalid.
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_ADMIN_KEY = 155,
  /*
   * A provided submit key was invalid.
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_SUBMIT_KEY = 156,
  /*
   * An attempted operation was not authorized (ie - a deleteTopic for a topic with no adminKey).
   */
  PROTO__RESPONSE_CODE_ENUM__UNAUTHORIZED = 157,
  /*
   * A ConsensusService message is empty.
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_TOPIC_MESSAGE = 158,
  /*
   * The autoRenewAccount specified is not a valid, active account.
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_AUTORENEW_ACCOUNT = 159,
  /*
   * An adminKey was not specified on the topic, so there must not be an autoRenewAccount.
   */
  PROTO__RESPONSE_CODE_ENUM__AUTORENEW_ACCOUNT_NOT_ALLOWED = 160,
  /*
   * The topic has expired, was not automatically renewed, and is in a 7 day grace period before the topic will be
   * deleted unrecoverably. This error response code will not be returned until autoRenew functionality is supported
   * by HAPI.
   */
  PROTO__RESPONSE_CODE_ENUM__TOPIC_EXPIRED = 162,
  /*
   * chunk number must be from 1 to total (chunks) inclusive.
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_CHUNK_NUMBER = 163,
  /*
   * For every chunk, the payer account that is part of initialTransactionID must match the Payer Account of this transaction. The entire initialTransactionID should match the transactionID of the first chunk, but this is not checked or enforced by Hedera except when the chunk number is 1.
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_CHUNK_TRANSACTION_ID = 164,
  /*
   * Account is frozen and cannot transact with the token
   */
  PROTO__RESPONSE_CODE_ENUM__ACCOUNT_FROZEN_FOR_TOKEN = 165,
  /*
   * An involved account already has more than <tt>tokens.maxPerAccount</tt> associations with non-deleted tokens.
   */
  PROTO__RESPONSE_CODE_ENUM__TOKENS_PER_ACCOUNT_LIMIT_EXCEEDED = 166,
  /*
   * The token is invalid or does not exist
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_TOKEN_ID = 167,
  /*
   * Invalid token decimals
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_TOKEN_DECIMALS = 168,
  /*
   * Invalid token initial supply
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_TOKEN_INITIAL_SUPPLY = 169,
  /*
   * Treasury Account does not exist or is deleted
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_TREASURY_ACCOUNT_FOR_TOKEN = 170,
  /*
   * Token Symbol is not UTF-8 capitalized alphabetical string
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_TOKEN_SYMBOL = 171,
  /*
   * Freeze key is not set on token
   */
  PROTO__RESPONSE_CODE_ENUM__TOKEN_HAS_NO_FREEZE_KEY = 172,
  /*
   * Amounts in transfer list are not net zero
   */
  PROTO__RESPONSE_CODE_ENUM__TRANSFERS_NOT_ZERO_SUM_FOR_TOKEN = 173,
  /*
   * A token symbol was not provided
   */
  PROTO__RESPONSE_CODE_ENUM__MISSING_TOKEN_SYMBOL = 174,
  /*
   * The provided token symbol was too long
   */
  PROTO__RESPONSE_CODE_ENUM__TOKEN_SYMBOL_TOO_LONG = 175,
  /*
   * KYC must be granted and account does not have KYC granted
   */
  PROTO__RESPONSE_CODE_ENUM__ACCOUNT_KYC_NOT_GRANTED_FOR_TOKEN = 176,
  /*
   * KYC key is not set on token
   */
  PROTO__RESPONSE_CODE_ENUM__TOKEN_HAS_NO_KYC_KEY = 177,
  /*
   * Token balance is not sufficient for the transaction
   */
  PROTO__RESPONSE_CODE_ENUM__INSUFFICIENT_TOKEN_BALANCE = 178,
  /*
   * Token transactions cannot be executed on deleted token
   */
  PROTO__RESPONSE_CODE_ENUM__TOKEN_WAS_DELETED = 179,
  /*
   * Supply key is not set on token
   */
  PROTO__RESPONSE_CODE_ENUM__TOKEN_HAS_NO_SUPPLY_KEY = 180,
  /*
   * Wipe key is not set on token
   */
  PROTO__RESPONSE_CODE_ENUM__TOKEN_HAS_NO_WIPE_KEY = 181,
  /*
   * The requested token mint amount would cause an invalid total supply
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_TOKEN_MINT_AMOUNT = 182,
  /*
   * The requested token burn amount would cause an invalid total supply
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_TOKEN_BURN_AMOUNT = 183,
  /*
   * A required token-account relationship is missing
   */
  PROTO__RESPONSE_CODE_ENUM__TOKEN_NOT_ASSOCIATED_TO_ACCOUNT = 184,
  /*
   * The target of a wipe operation was the token treasury account
   */
  PROTO__RESPONSE_CODE_ENUM__CANNOT_WIPE_TOKEN_TREASURY_ACCOUNT = 185,
  /*
   * The provided KYC key was invalid.
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_KYC_KEY = 186,
  /*
   * The provided wipe key was invalid.
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_WIPE_KEY = 187,
  /*
   * The provided freeze key was invalid.
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_FREEZE_KEY = 188,
  /*
   * The provided supply key was invalid.
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_SUPPLY_KEY = 189,
  /*
   * Token Name is not provided
   */
  PROTO__RESPONSE_CODE_ENUM__MISSING_TOKEN_NAME = 190,
  /*
   * Token Name is too long
   */
  PROTO__RESPONSE_CODE_ENUM__TOKEN_NAME_TOO_LONG = 191,
  /*
   * The provided wipe amount must not be negative, zero or bigger than the token holder balance
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_WIPING_AMOUNT = 192,
  /*
   * Token does not have Admin key set, thus update/delete transactions cannot be performed
   */
  PROTO__RESPONSE_CODE_ENUM__TOKEN_IS_IMMUTABLE = 193,
  /*
   * An <tt>associateToken</tt> operation specified a token already associated to the account
   */
  PROTO__RESPONSE_CODE_ENUM__TOKEN_ALREADY_ASSOCIATED_TO_ACCOUNT = 194,
  /*
   * An attempted operation is invalid until all token balances for the target account are zero
   */
  PROTO__RESPONSE_CODE_ENUM__TRANSACTION_REQUIRES_ZERO_TOKEN_BALANCES = 195,
  /*
   * An attempted operation is invalid because the account is a treasury
   */
  PROTO__RESPONSE_CODE_ENUM__ACCOUNT_IS_TREASURY = 196,
  /*
   * Same TokenIDs present in the token list
   */
  PROTO__RESPONSE_CODE_ENUM__TOKEN_ID_REPEATED_IN_TOKEN_LIST = 197,
  /*
   * Exceeded the number of token transfers (both from and to) allowed for token transfer list
   */
  PROTO__RESPONSE_CODE_ENUM__TOKEN_TRANSFER_LIST_SIZE_LIMIT_EXCEEDED = 198,
  /*
   * TokenTransfersTransactionBody has no TokenTransferList
   */
  PROTO__RESPONSE_CODE_ENUM__EMPTY_TOKEN_TRANSFER_BODY = 199,
  /*
   * TokenTransfersTransactionBody has a TokenTransferList with no AccountAmounts
   */
  PROTO__RESPONSE_CODE_ENUM__EMPTY_TOKEN_TRANSFER_ACCOUNT_AMOUNTS = 200,
  /*
   * The Scheduled entity does not exist; or has now expired, been deleted, or been executed
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_SCHEDULE_ID = 201,
  /*
   * The Scheduled entity cannot be modified. Admin key not set
   */
  PROTO__RESPONSE_CODE_ENUM__SCHEDULE_IS_IMMUTABLE = 202,
  /*
   * The provided Scheduled Payer does not exist
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_SCHEDULE_PAYER_ID = 203,
  /*
   * The Schedule Create Transaction TransactionID account does not exist
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_SCHEDULE_ACCOUNT_ID = 204,
  /*
   * The provided sig map did not contain any new valid signatures from required signers of the scheduled transaction
   */
  PROTO__RESPONSE_CODE_ENUM__NO_NEW_VALID_SIGNATURES = 205,
  /*
   * The required signers for a scheduled transaction cannot be resolved, for example because they do not exist or have been deleted
   */
  PROTO__RESPONSE_CODE_ENUM__UNRESOLVABLE_REQUIRED_SIGNERS = 206,
  /*
   * Only whitelisted transaction types may be scheduled
   */
  PROTO__RESPONSE_CODE_ENUM__SCHEDULED_TRANSACTION_NOT_IN_WHITELIST = 207,
  /*
   * At least one of the signatures in the provided sig map did not represent a valid signature for any required signer
   */
  PROTO__RESPONSE_CODE_ENUM__SOME_SIGNATURES_WERE_INVALID = 208,
  /*
   * The scheduled field in the TransactionID may not be set to true
   */
  PROTO__RESPONSE_CODE_ENUM__TRANSACTION_ID_FIELD_NOT_ALLOWED = 209,
  /*
   * A schedule already exists with the same identifying fields of an attempted ScheduleCreate (that is, all fields other than scheduledPayerAccountID)
   */
  PROTO__RESPONSE_CODE_ENUM__IDENTICAL_SCHEDULE_ALREADY_CREATED = 210,
  /*
   * A string field in the transaction has a UTF-8 encoding with the prohibited zero byte
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_ZERO_BYTE_IN_STRING = 211,
  /*
   * A schedule being signed or deleted has already been deleted
   */
  PROTO__RESPONSE_CODE_ENUM__SCHEDULE_ALREADY_DELETED = 212,
  /*
   * A schedule being signed or deleted has already been executed
   */
  PROTO__RESPONSE_CODE_ENUM__SCHEDULE_ALREADY_EXECUTED = 213,
  /*
   * ConsensusSubmitMessage request's message size is larger than allowed.
   */
  PROTO__RESPONSE_CODE_ENUM__MESSAGE_SIZE_TOO_LARGE = 214,
  /*
   * An operation was assigned to more than one throttle group in a given bucket
   */
  PROTO__RESPONSE_CODE_ENUM__OPERATION_REPEATED_IN_BUCKET_GROUPS = 215,
  /*
   * The capacity needed to satisfy all opsPerSec groups in a bucket overflowed a signed 8-byte integral type
   */
  PROTO__RESPONSE_CODE_ENUM__BUCKET_CAPACITY_OVERFLOW = 216,
  /*
   * Given the network size in the address book, the node-level capacity for an operation would never be enough to accept a single request; usually means a bucket burstPeriod should be increased
   */
  PROTO__RESPONSE_CODE_ENUM__NODE_CAPACITY_NOT_SUFFICIENT_FOR_OPERATION = 217,
  /*
   * A bucket was defined without any throttle groups
   */
  PROTO__RESPONSE_CODE_ENUM__BUCKET_HAS_NO_THROTTLE_GROUPS = 218,
  /*
   * A throttle group was granted zero opsPerSec
   */
  PROTO__RESPONSE_CODE_ENUM__THROTTLE_GROUP_HAS_ZERO_OPS_PER_SEC = 219,
  /*
   * The throttle definitions file was updated, but some supported operations were not assigned a bucket
   */
  PROTO__RESPONSE_CODE_ENUM__SUCCESS_BUT_MISSING_EXPECTED_OPERATION = 220,
  /*
   * The new contents for the throttle definitions system file were not valid protobuf
   */
  PROTO__RESPONSE_CODE_ENUM__UNPARSEABLE_THROTTLE_DEFINITIONS = 221,
  /*
   * The new throttle definitions system file were invalid, and no more specific error could be divined
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_THROTTLE_DEFINITIONS = 222,
  /*
   * The transaction references an account which has passed its expiration without renewal funds available, and currently remains in the ledger only because of the grace period given to expired entities
   */
  PROTO__RESPONSE_CODE_ENUM__ACCOUNT_EXPIRED_AND_PENDING_REMOVAL = 223,
  /*
   * Invalid token max supply
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_TOKEN_MAX_SUPPLY = 224,
  /*
   * Invalid token nft serial number
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_TOKEN_NFT_SERIAL_NUMBER = 225,
  /*
   * Invalid nft id
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_NFT_ID = 226,
  /*
   * Nft metadata is too long
   */
  PROTO__RESPONSE_CODE_ENUM__METADATA_TOO_LONG = 227,
  /*
   * Repeated operations count exceeds the limit
   */
  PROTO__RESPONSE_CODE_ENUM__BATCH_SIZE_LIMIT_EXCEEDED = 228,
  /*
   * The range of data to be gathered is out of the set boundaries
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_QUERY_RANGE = 229,
  /*
   * A custom fractional fee set a denominator of zero
   */
  PROTO__RESPONSE_CODE_ENUM__FRACTION_DIVIDES_BY_ZERO = 230,
  /*
   * The transaction payer could not afford a custom fee
   */
  PROTO__RESPONSE_CODE_ENUM__INSUFFICIENT_PAYER_BALANCE_FOR_CUSTOM_FEE = 231,
  /*
   * More than 10 custom fees were specified
   */
  PROTO__RESPONSE_CODE_ENUM__CUSTOM_FEES_LIST_TOO_LONG = 232,
  /*
   * Any of the feeCollector accounts for customFees is invalid
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_CUSTOM_FEE_COLLECTOR = 233,
  /*
   * Any of the token Ids in customFees is invalid
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_TOKEN_ID_IN_CUSTOM_FEES = 234,
  /*
   * Any of the token Ids in customFees are not associated to feeCollector
   */
  PROTO__RESPONSE_CODE_ENUM__TOKEN_NOT_ASSOCIATED_TO_FEE_COLLECTOR = 235,
  /*
   * A token cannot have more units minted due to its configured supply ceiling
   */
  PROTO__RESPONSE_CODE_ENUM__TOKEN_MAX_SUPPLY_REACHED = 236,
  /*
   * The transaction attempted to move an NFT serial number from an account other than its owner
   */
  PROTO__RESPONSE_CODE_ENUM__SENDER_DOES_NOT_OWN_NFT_SERIAL_NO = 237,
  /*
   * A custom fee schedule entry did not specify either a fixed or fractional fee
   */
  PROTO__RESPONSE_CODE_ENUM__CUSTOM_FEE_NOT_FULLY_SPECIFIED = 238,
  /*
   * Only positive fees may be assessed at this time
   */
  PROTO__RESPONSE_CODE_ENUM__CUSTOM_FEE_MUST_BE_POSITIVE = 239,
  /*
   * Fee schedule key is not set on token
   */
  PROTO__RESPONSE_CODE_ENUM__TOKEN_HAS_NO_FEE_SCHEDULE_KEY = 240,
  /*
   * A fractional custom fee exceeded the range of a 64-bit signed integer
   */
  PROTO__RESPONSE_CODE_ENUM__CUSTOM_FEE_OUTSIDE_NUMERIC_RANGE = 241,
  /*
   * The sum of all custom fractional fees must be strictly less than 1
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_CUSTOM_FRACTIONAL_FEES_SUM = 242,
  /*
   * Each fractional custom fee must have its maximum_amount, if specified, at least its minimum_amount
   */
  PROTO__RESPONSE_CODE_ENUM__FRACTIONAL_FEE_MAX_AMOUNT_LESS_THAN_MIN_AMOUNT = 243,
  /*
   * A fee schedule update tried to clear the custom fees from a token whose fee schedule was already empty
   */
  PROTO__RESPONSE_CODE_ENUM__CUSTOM_SCHEDULE_ALREADY_HAS_NO_FEES = 244,
  /*
   * Only tokens of type FUNGIBLE_COMMON can be used to as fee schedule denominations
   */
  PROTO__RESPONSE_CODE_ENUM__CUSTOM_FEE_DENOMINATION_MUST_BE_FUNGIBLE_COMMON = 245,
  /*
   * Only tokens of type FUNGIBLE_COMMON can have fractional fees
   */
  PROTO__RESPONSE_CODE_ENUM__CUSTOM_FRACTIONAL_FEE_ONLY_ALLOWED_FOR_FUNGIBLE_COMMON = 246,
  /*
   * The provided custom fee schedule key was invalid
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_CUSTOM_FEE_SCHEDULE_KEY = 247,
  /*
   * The requested token mint metadata was invalid
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_TOKEN_MINT_METADATA = 248,
  /*
   * The requested token burn metadata was invalid
   */
  PROTO__RESPONSE_CODE_ENUM__INVALID_TOKEN_BURN_METADATA = 249,
  /*
   * The treasury for a unique token cannot be changed until it owns no NFTs
   */
  PROTO__RESPONSE_CODE_ENUM__CURRENT_TREASURY_STILL_OWNS_NFTS = 250,
  /*
   * An account cannot be dissociated from a unique token if it owns NFTs for the token
   */
  PROTO__RESPONSE_CODE_ENUM__ACCOUNT_STILL_OWNS_NFTS = 251,
  /*
   * A NFT can only be burned when owned by the unique token's treasury
   */
  PROTO__RESPONSE_CODE_ENUM__TREASURY_MUST_OWN_BURNED_NFT = 252,
  /*
   * An account did not own the NFT to be wiped
   */
  PROTO__RESPONSE_CODE_ENUM__ACCOUNT_DOES_NOT_OWN_WIPED_NFT = 253,
  /*
   * An AccountAmount token transfers list referenced a token type other than FUNGIBLE_COMMON
   */
  PROTO__RESPONSE_CODE_ENUM__ACCOUNT_AMOUNT_TRANSFERS_ONLY_ALLOWED_FOR_FUNGIBLE_COMMON = 254,
  /*
   * All the NFTs allowed in the current price regime have already been minted
   */
  PROTO__RESPONSE_CODE_ENUM__MAX_NFTS_IN_PRICE_REGIME_HAVE_BEEN_MINTED = 255,
  /*
   * The payer account has been marked as deleted
   */
  PROTO__RESPONSE_CODE_ENUM__PAYER_ACCOUNT_DELETED = 256,
  /*
   * The reference chain of custom fees for a transferred token exceeded the maximum length of 2
   */
  PROTO__RESPONSE_CODE_ENUM__CUSTOM_FEE_CHARGING_EXCEEDED_MAX_RECURSION_DEPTH = 257,
  /*
   * More than 20 balance adjustments were to satisfy a CryptoTransfer and its implied custom fee payments
   */
  PROTO__RESPONSE_CODE_ENUM__CUSTOM_FEE_CHARGING_EXCEEDED_MAX_ACCOUNT_AMOUNTS = 258
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(PROTO__RESPONSE_CODE_ENUM)
} Proto__ResponseCodeEnum;

/* --- messages --- */

/* --- per-message closures --- */


/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    proto__response_code_enum__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_ResponseCode_2eproto__INCLUDED */
