/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ScheduleService.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ScheduleService.pb-c.h"
static const ProtobufCMethodDescriptor proto__schedule_service__method_descriptors[4] =
{
  { "createSchedule", &proto__transaction__descriptor, &proto__transaction_response__descriptor },
  { "signSchedule", &proto__transaction__descriptor, &proto__transaction_response__descriptor },
  { "deleteSchedule", &proto__transaction__descriptor, &proto__transaction_response__descriptor },
  { "getScheduleInfo", &proto__query__descriptor, &proto__response__descriptor },
};
const unsigned proto__schedule_service__method_indices_by_name[] = {
  0,        /* createSchedule */
  2,        /* deleteSchedule */
  3,        /* getScheduleInfo */
  1         /* signSchedule */
};
const ProtobufCServiceDescriptor proto__schedule_service__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "proto.ScheduleService",
  "ScheduleService",
  "Proto__ScheduleService",
  "proto",
  4,
  proto__schedule_service__method_descriptors,
  proto__schedule_service__method_indices_by_name
};
void proto__schedule_service__create_schedule(ProtobufCService *service,
                                              const Proto__Transaction *input,
                                              Proto__TransactionResponse_Closure closure,
                                              void *closure_data)
{
  assert(service->descriptor == &proto__schedule_service__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void proto__schedule_service__sign_schedule(ProtobufCService *service,
                                            const Proto__Transaction *input,
                                            Proto__TransactionResponse_Closure closure,
                                            void *closure_data)
{
  assert(service->descriptor == &proto__schedule_service__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void proto__schedule_service__delete_schedule(ProtobufCService *service,
                                              const Proto__Transaction *input,
                                              Proto__TransactionResponse_Closure closure,
                                              void *closure_data)
{
  assert(service->descriptor == &proto__schedule_service__descriptor);
  service->invoke(service, 2, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void proto__schedule_service__get_schedule_info(ProtobufCService *service,
                                                const Proto__Query *input,
                                                Proto__Response_Closure closure,
                                                void *closure_data)
{
  assert(service->descriptor == &proto__schedule_service__descriptor);
  service->invoke(service, 3, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void proto__schedule_service__init (Proto__ScheduleService_Service *service,
                                    Proto__ScheduleService_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &proto__schedule_service__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
