/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ScheduleCreate.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ScheduleCreate.pb-c.h"
void   proto__schedule_create_transaction_body__init
                     (Proto__ScheduleCreateTransactionBody         *message)
{
  static const Proto__ScheduleCreateTransactionBody init_value = PROTO__SCHEDULE_CREATE_TRANSACTION_BODY__INIT;
  *message = init_value;
}
size_t proto__schedule_create_transaction_body__get_packed_size
                     (const Proto__ScheduleCreateTransactionBody *message)
{
  assert(message->base.descriptor == &proto__schedule_create_transaction_body__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__schedule_create_transaction_body__pack
                     (const Proto__ScheduleCreateTransactionBody *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__schedule_create_transaction_body__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__schedule_create_transaction_body__pack_to_buffer
                     (const Proto__ScheduleCreateTransactionBody *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__schedule_create_transaction_body__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__ScheduleCreateTransactionBody *
       proto__schedule_create_transaction_body__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__ScheduleCreateTransactionBody *)
     protobuf_c_message_unpack (&proto__schedule_create_transaction_body__descriptor,
                                allocator, len, data);
}
void   proto__schedule_create_transaction_body__free_unpacked
                     (Proto__ScheduleCreateTransactionBody *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__schedule_create_transaction_body__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor proto__schedule_create_transaction_body__field_descriptors[4] =
{
  {
    "scheduledTransactionBody",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__ScheduleCreateTransactionBody, scheduledtransactionbody),
    &proto__schedulable_transaction_body__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "memo",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Proto__ScheduleCreateTransactionBody, memo),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "adminKey",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__ScheduleCreateTransactionBody, adminkey),
    &proto__key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payerAccountID",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__ScheduleCreateTransactionBody, payeraccountid),
    &proto__account_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__schedule_create_transaction_body__field_indices_by_name[] = {
  2,   /* field[2] = adminKey */
  1,   /* field[1] = memo */
  3,   /* field[3] = payerAccountID */
  0,   /* field[0] = scheduledTransactionBody */
};
static const ProtobufCIntRange proto__schedule_create_transaction_body__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor proto__schedule_create_transaction_body__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.ScheduleCreateTransactionBody",
  "ScheduleCreateTransactionBody",
  "Proto__ScheduleCreateTransactionBody",
  "proto",
  sizeof(Proto__ScheduleCreateTransactionBody),
  4,
  proto__schedule_create_transaction_body__field_descriptors,
  proto__schedule_create_transaction_body__field_indices_by_name,
  1,  proto__schedule_create_transaction_body__number_ranges,
  (ProtobufCMessageInit) proto__schedule_create_transaction_body__init,
  NULL,NULL,NULL    /* reserved[123] */
};
