/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ThrottleDefinitions.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ThrottleDefinitions.pb-c.h"
void   proto__throttle_group__init
                     (Proto__ThrottleGroup         *message)
{
  static const Proto__ThrottleGroup init_value = PROTO__THROTTLE_GROUP__INIT;
  *message = init_value;
}
size_t proto__throttle_group__get_packed_size
                     (const Proto__ThrottleGroup *message)
{
  assert(message->base.descriptor == &proto__throttle_group__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__throttle_group__pack
                     (const Proto__ThrottleGroup *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__throttle_group__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__throttle_group__pack_to_buffer
                     (const Proto__ThrottleGroup *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__throttle_group__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__ThrottleGroup *
       proto__throttle_group__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__ThrottleGroup *)
     protobuf_c_message_unpack (&proto__throttle_group__descriptor,
                                allocator, len, data);
}
void   proto__throttle_group__free_unpacked
                     (Proto__ThrottleGroup *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__throttle_group__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__throttle_bucket__init
                     (Proto__ThrottleBucket         *message)
{
  static const Proto__ThrottleBucket init_value = PROTO__THROTTLE_BUCKET__INIT;
  *message = init_value;
}
size_t proto__throttle_bucket__get_packed_size
                     (const Proto__ThrottleBucket *message)
{
  assert(message->base.descriptor == &proto__throttle_bucket__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__throttle_bucket__pack
                     (const Proto__ThrottleBucket *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__throttle_bucket__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__throttle_bucket__pack_to_buffer
                     (const Proto__ThrottleBucket *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__throttle_bucket__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__ThrottleBucket *
       proto__throttle_bucket__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__ThrottleBucket *)
     protobuf_c_message_unpack (&proto__throttle_bucket__descriptor,
                                allocator, len, data);
}
void   proto__throttle_bucket__free_unpacked
                     (Proto__ThrottleBucket *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__throttle_bucket__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__throttle_definitions__init
                     (Proto__ThrottleDefinitions         *message)
{
  static const Proto__ThrottleDefinitions init_value = PROTO__THROTTLE_DEFINITIONS__INIT;
  *message = init_value;
}
size_t proto__throttle_definitions__get_packed_size
                     (const Proto__ThrottleDefinitions *message)
{
  assert(message->base.descriptor == &proto__throttle_definitions__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__throttle_definitions__pack
                     (const Proto__ThrottleDefinitions *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__throttle_definitions__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__throttle_definitions__pack_to_buffer
                     (const Proto__ThrottleDefinitions *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__throttle_definitions__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__ThrottleDefinitions *
       proto__throttle_definitions__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__ThrottleDefinitions *)
     protobuf_c_message_unpack (&proto__throttle_definitions__descriptor,
                                allocator, len, data);
}
void   proto__throttle_definitions__free_unpacked
                     (Proto__ThrottleDefinitions *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__throttle_definitions__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor proto__throttle_group__field_descriptors[2] =
{
  {
    "operations",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Proto__ThrottleGroup, n_operations),
    offsetof(Proto__ThrottleGroup, operations),
    &proto__hedera_functionality__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "milliOpsPerSec",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Proto__ThrottleGroup, milliopspersec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__throttle_group__field_indices_by_name[] = {
  1,   /* field[1] = milliOpsPerSec */
  0,   /* field[0] = operations */
};
static const ProtobufCIntRange proto__throttle_group__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto__throttle_group__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.ThrottleGroup",
  "ThrottleGroup",
  "Proto__ThrottleGroup",
  "proto",
  sizeof(Proto__ThrottleGroup),
  2,
  proto__throttle_group__field_descriptors,
  proto__throttle_group__field_indices_by_name,
  1,  proto__throttle_group__number_ranges,
  (ProtobufCMessageInit) proto__throttle_group__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__throttle_bucket__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Proto__ThrottleBucket, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "burstPeriodMs",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Proto__ThrottleBucket, burstperiodms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "throttleGroups",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Proto__ThrottleBucket, n_throttlegroups),
    offsetof(Proto__ThrottleBucket, throttlegroups),
    &proto__throttle_group__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__throttle_bucket__field_indices_by_name[] = {
  1,   /* field[1] = burstPeriodMs */
  0,   /* field[0] = name */
  2,   /* field[2] = throttleGroups */
};
static const ProtobufCIntRange proto__throttle_bucket__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor proto__throttle_bucket__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.ThrottleBucket",
  "ThrottleBucket",
  "Proto__ThrottleBucket",
  "proto",
  sizeof(Proto__ThrottleBucket),
  3,
  proto__throttle_bucket__field_descriptors,
  proto__throttle_bucket__field_indices_by_name,
  1,  proto__throttle_bucket__number_ranges,
  (ProtobufCMessageInit) proto__throttle_bucket__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__throttle_definitions__field_descriptors[1] =
{
  {
    "throttleBuckets",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Proto__ThrottleDefinitions, n_throttlebuckets),
    offsetof(Proto__ThrottleDefinitions, throttlebuckets),
    &proto__throttle_bucket__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__throttle_definitions__field_indices_by_name[] = {
  0,   /* field[0] = throttleBuckets */
};
static const ProtobufCIntRange proto__throttle_definitions__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor proto__throttle_definitions__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.ThrottleDefinitions",
  "ThrottleDefinitions",
  "Proto__ThrottleDefinitions",
  "proto",
  sizeof(Proto__ThrottleDefinitions),
  1,
  proto__throttle_definitions__field_descriptors,
  proto__throttle_definitions__field_indices_by_name,
  1,  proto__throttle_definitions__number_ranges,
  (ProtobufCMessageInit) proto__throttle_definitions__init,
  NULL,NULL,NULL    /* reserved[123] */
};
