/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: TokenCreate.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "TokenCreate.pb-c.h"
void   proto__token_create_transaction_body__init
                     (Proto__TokenCreateTransactionBody         *message)
{
  static const Proto__TokenCreateTransactionBody init_value = PROTO__TOKEN_CREATE_TRANSACTION_BODY__INIT;
  *message = init_value;
}
size_t proto__token_create_transaction_body__get_packed_size
                     (const Proto__TokenCreateTransactionBody *message)
{
  assert(message->base.descriptor == &proto__token_create_transaction_body__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__token_create_transaction_body__pack
                     (const Proto__TokenCreateTransactionBody *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__token_create_transaction_body__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__token_create_transaction_body__pack_to_buffer
                     (const Proto__TokenCreateTransactionBody *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__token_create_transaction_body__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__TokenCreateTransactionBody *
       proto__token_create_transaction_body__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__TokenCreateTransactionBody *)
     protobuf_c_message_unpack (&proto__token_create_transaction_body__descriptor,
                                allocator, len, data);
}
void   proto__token_create_transaction_body__free_unpacked
                     (Proto__TokenCreateTransactionBody *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__token_create_transaction_body__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor proto__token_create_transaction_body__field_descriptors[20] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenCreateTransactionBody, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "symbol",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenCreateTransactionBody, symbol),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "decimals",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenCreateTransactionBody, decimals),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "initialSupply",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenCreateTransactionBody, initialsupply),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "treasury",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenCreateTransactionBody, treasury),
    &proto__account_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "adminKey",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenCreateTransactionBody, adminkey),
    &proto__key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kycKey",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenCreateTransactionBody, kyckey),
    &proto__key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "freezeKey",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenCreateTransactionBody, freezekey),
    &proto__key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wipeKey",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenCreateTransactionBody, wipekey),
    &proto__key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "supplyKey",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenCreateTransactionBody, supplykey),
    &proto__key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "freezeDefault",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenCreateTransactionBody, freezedefault),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "expiry",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenCreateTransactionBody, expiry),
    &proto__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "autoRenewAccount",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenCreateTransactionBody, autorenewaccount),
    &proto__account_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "autoRenewPeriod",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenCreateTransactionBody, autorenewperiod),
    &proto__duration__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "memo",
    16,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenCreateTransactionBody, memo),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tokenType",
    17,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenCreateTransactionBody, tokentype),
    &proto__token_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "supplyType",
    18,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenCreateTransactionBody, supplytype),
    &proto__token_supply_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maxSupply",
    19,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenCreateTransactionBody, maxsupply),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fee_schedule_key",
    20,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenCreateTransactionBody, fee_schedule_key),
    &proto__key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "custom_fees",
    21,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Proto__TokenCreateTransactionBody, n_custom_fees),
    offsetof(Proto__TokenCreateTransactionBody, custom_fees),
    &proto__custom_fee__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__token_create_transaction_body__field_indices_by_name[] = {
  5,   /* field[5] = adminKey */
  12,   /* field[12] = autoRenewAccount */
  13,   /* field[13] = autoRenewPeriod */
  19,   /* field[19] = custom_fees */
  2,   /* field[2] = decimals */
  11,   /* field[11] = expiry */
  18,   /* field[18] = fee_schedule_key */
  10,   /* field[10] = freezeDefault */
  7,   /* field[7] = freezeKey */
  3,   /* field[3] = initialSupply */
  6,   /* field[6] = kycKey */
  17,   /* field[17] = maxSupply */
  14,   /* field[14] = memo */
  0,   /* field[0] = name */
  9,   /* field[9] = supplyKey */
  16,   /* field[16] = supplyType */
  1,   /* field[1] = symbol */
  15,   /* field[15] = tokenType */
  4,   /* field[4] = treasury */
  8,   /* field[8] = wipeKey */
};
static const ProtobufCIntRange proto__token_create_transaction_body__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 13, 11 },
  { 0, 20 }
};
const ProtobufCMessageDescriptor proto__token_create_transaction_body__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.TokenCreateTransactionBody",
  "TokenCreateTransactionBody",
  "Proto__TokenCreateTransactionBody",
  "proto",
  sizeof(Proto__TokenCreateTransactionBody),
  20,
  proto__token_create_transaction_body__field_descriptors,
  proto__token_create_transaction_body__field_indices_by_name,
  2,  proto__token_create_transaction_body__number_ranges,
  (ProtobufCMessageInit) proto__token_create_transaction_body__init,
  NULL,NULL,NULL    /* reserved[123] */
};
