/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: TokenGetNftInfos.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "TokenGetNftInfos.pb-c.h"
void   proto__token_get_nft_infos_query__init
                     (Proto__TokenGetNftInfosQuery         *message)
{
  static const Proto__TokenGetNftInfosQuery init_value = PROTO__TOKEN_GET_NFT_INFOS_QUERY__INIT;
  *message = init_value;
}
size_t proto__token_get_nft_infos_query__get_packed_size
                     (const Proto__TokenGetNftInfosQuery *message)
{
  assert(message->base.descriptor == &proto__token_get_nft_infos_query__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__token_get_nft_infos_query__pack
                     (const Proto__TokenGetNftInfosQuery *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__token_get_nft_infos_query__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__token_get_nft_infos_query__pack_to_buffer
                     (const Proto__TokenGetNftInfosQuery *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__token_get_nft_infos_query__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__TokenGetNftInfosQuery *
       proto__token_get_nft_infos_query__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__TokenGetNftInfosQuery *)
     protobuf_c_message_unpack (&proto__token_get_nft_infos_query__descriptor,
                                allocator, len, data);
}
void   proto__token_get_nft_infos_query__free_unpacked
                     (Proto__TokenGetNftInfosQuery *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__token_get_nft_infos_query__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__token_get_nft_infos_response__init
                     (Proto__TokenGetNftInfosResponse         *message)
{
  static const Proto__TokenGetNftInfosResponse init_value = PROTO__TOKEN_GET_NFT_INFOS_RESPONSE__INIT;
  *message = init_value;
}
size_t proto__token_get_nft_infos_response__get_packed_size
                     (const Proto__TokenGetNftInfosResponse *message)
{
  assert(message->base.descriptor == &proto__token_get_nft_infos_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__token_get_nft_infos_response__pack
                     (const Proto__TokenGetNftInfosResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__token_get_nft_infos_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__token_get_nft_infos_response__pack_to_buffer
                     (const Proto__TokenGetNftInfosResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__token_get_nft_infos_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__TokenGetNftInfosResponse *
       proto__token_get_nft_infos_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__TokenGetNftInfosResponse *)
     protobuf_c_message_unpack (&proto__token_get_nft_infos_response__descriptor,
                                allocator, len, data);
}
void   proto__token_get_nft_infos_response__free_unpacked
                     (Proto__TokenGetNftInfosResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__token_get_nft_infos_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor proto__token_get_nft_infos_query__field_descriptors[4] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenGetNftInfosQuery, header),
    &proto__query_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tokenID",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenGetNftInfosQuery, tokenid),
    &proto__token_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenGetNftInfosQuery, start),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenGetNftInfosQuery, end),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__token_get_nft_infos_query__field_indices_by_name[] = {
  3,   /* field[3] = end */
  0,   /* field[0] = header */
  2,   /* field[2] = start */
  1,   /* field[1] = tokenID */
};
static const ProtobufCIntRange proto__token_get_nft_infos_query__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor proto__token_get_nft_infos_query__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.TokenGetNftInfosQuery",
  "TokenGetNftInfosQuery",
  "Proto__TokenGetNftInfosQuery",
  "proto",
  sizeof(Proto__TokenGetNftInfosQuery),
  4,
  proto__token_get_nft_infos_query__field_descriptors,
  proto__token_get_nft_infos_query__field_indices_by_name,
  1,  proto__token_get_nft_infos_query__number_ranges,
  (ProtobufCMessageInit) proto__token_get_nft_infos_query__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__token_get_nft_infos_response__field_descriptors[3] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenGetNftInfosResponse, header),
    &proto__response_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tokenID",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenGetNftInfosResponse, tokenid),
    &proto__token_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nfts",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Proto__TokenGetNftInfosResponse, n_nfts),
    offsetof(Proto__TokenGetNftInfosResponse, nfts),
    &proto__token_nft_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__token_get_nft_infos_response__field_indices_by_name[] = {
  0,   /* field[0] = header */
  2,   /* field[2] = nfts */
  1,   /* field[1] = tokenID */
};
static const ProtobufCIntRange proto__token_get_nft_infos_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor proto__token_get_nft_infos_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.TokenGetNftInfosResponse",
  "TokenGetNftInfosResponse",
  "Proto__TokenGetNftInfosResponse",
  "proto",
  sizeof(Proto__TokenGetNftInfosResponse),
  3,
  proto__token_get_nft_infos_response__field_descriptors,
  proto__token_get_nft_infos_response__field_indices_by_name,
  1,  proto__token_get_nft_infos_response__number_ranges,
  (ProtobufCMessageInit) proto__token_get_nft_infos_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
