/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: TokenAssociate.proto */

#ifndef PROTOBUF_C_TokenAssociate_2eproto__INCLUDED
#define PROTOBUF_C_TokenAssociate_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "BasicTypes.pb-c.h"

typedef struct Proto__TokenAssociateTransactionBody Proto__TokenAssociateTransactionBody;


/* --- enums --- */


/* --- messages --- */

/*
 * Associates the provided account with the provided tokens. Must be signed by the provided Account's key.
 *If the provided account is not found, the transaction will resolve to INVALID_ACCOUNT_ID.
 *If the provided account has been deleted, the transaction will resolve to ACCOUNT_DELETED.
 *If any of the provided tokens is not found, the transaction will resolve to INVALID_TOKEN_REF.
 *If any of the provided tokens has been deleted, the transaction will resolve to TOKEN_WAS_DELETED.
 *If an association between the provided account and any of the tokens already exists, the transaction will resolve to TOKEN_ALREADY_ASSOCIATED_TO_ACCOUNT.
 *If the provided account's associations count exceed the constraint of maximum token associations per account, the transaction will resolve to TOKENS_PER_ACCOUNT_LIMIT_EXCEEDED.
 *On success, associations between the provided account and tokens are made and the account is ready to interact with the tokens.
 */
struct  Proto__TokenAssociateTransactionBody
{
  ProtobufCMessage base;
  /*
   * The account to be associated with the provided tokens
   */
  Proto__AccountID *account;
  /*
   * The tokens to be associated with the provided account. In the case of NON_FUNGIBLE_UNIQUE Type, once an account is associated, it can hold any number of NFTs (serial numbers) of that token type
   */
  size_t n_tokens;
  Proto__TokenID **tokens;
};
#define PROTO__TOKEN_ASSOCIATE_TRANSACTION_BODY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__token_associate_transaction_body__descriptor) \
    , NULL, 0,NULL }


/* Proto__TokenAssociateTransactionBody methods */
void   proto__token_associate_transaction_body__init
                     (Proto__TokenAssociateTransactionBody         *message);
size_t proto__token_associate_transaction_body__get_packed_size
                     (const Proto__TokenAssociateTransactionBody   *message);
size_t proto__token_associate_transaction_body__pack
                     (const Proto__TokenAssociateTransactionBody   *message,
                      uint8_t             *out);
size_t proto__token_associate_transaction_body__pack_to_buffer
                     (const Proto__TokenAssociateTransactionBody   *message,
                      ProtobufCBuffer     *buffer);
Proto__TokenAssociateTransactionBody *
       proto__token_associate_transaction_body__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__token_associate_transaction_body__free_unpacked
                     (Proto__TokenAssociateTransactionBody *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Proto__TokenAssociateTransactionBody_Closure)
                 (const Proto__TokenAssociateTransactionBody *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor proto__token_associate_transaction_body__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_TokenAssociate_2eproto__INCLUDED */
