/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: TokenBurn.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "TokenBurn.pb-c.h"
void   proto__token_burn_transaction_body__init
                     (Proto__TokenBurnTransactionBody         *message)
{
  static const Proto__TokenBurnTransactionBody init_value = PROTO__TOKEN_BURN_TRANSACTION_BODY__INIT;
  *message = init_value;
}
size_t proto__token_burn_transaction_body__get_packed_size
                     (const Proto__TokenBurnTransactionBody *message)
{
  assert(message->base.descriptor == &proto__token_burn_transaction_body__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__token_burn_transaction_body__pack
                     (const Proto__TokenBurnTransactionBody *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__token_burn_transaction_body__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__token_burn_transaction_body__pack_to_buffer
                     (const Proto__TokenBurnTransactionBody *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__token_burn_transaction_body__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__TokenBurnTransactionBody *
       proto__token_burn_transaction_body__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__TokenBurnTransactionBody *)
     protobuf_c_message_unpack (&proto__token_burn_transaction_body__descriptor,
                                allocator, len, data);
}
void   proto__token_burn_transaction_body__free_unpacked
                     (Proto__TokenBurnTransactionBody *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__token_burn_transaction_body__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor proto__token_burn_transaction_body__field_descriptors[3] =
{
  {
    "token",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenBurnTransactionBody, token),
    &proto__token_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "amount",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenBurnTransactionBody, amount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serialNumbers",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Proto__TokenBurnTransactionBody, n_serialnumbers),
    offsetof(Proto__TokenBurnTransactionBody, serialnumbers),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__token_burn_transaction_body__field_indices_by_name[] = {
  1,   /* field[1] = amount */
  2,   /* field[2] = serialNumbers */
  0,   /* field[0] = token */
};
static const ProtobufCIntRange proto__token_burn_transaction_body__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor proto__token_burn_transaction_body__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.TokenBurnTransactionBody",
  "TokenBurnTransactionBody",
  "Proto__TokenBurnTransactionBody",
  "proto",
  sizeof(Proto__TokenBurnTransactionBody),
  3,
  proto__token_burn_transaction_body__field_descriptors,
  proto__token_burn_transaction_body__field_indices_by_name,
  1,  proto__token_burn_transaction_body__number_ranges,
  (ProtobufCMessageInit) proto__token_burn_transaction_body__init,
  NULL,NULL,NULL    /* reserved[123] */
};
