/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: TokenGetInfo.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "TokenGetInfo.pb-c.h"
void   proto__token_get_info_query__init
                     (Proto__TokenGetInfoQuery         *message)
{
  static const Proto__TokenGetInfoQuery init_value = PROTO__TOKEN_GET_INFO_QUERY__INIT;
  *message = init_value;
}
size_t proto__token_get_info_query__get_packed_size
                     (const Proto__TokenGetInfoQuery *message)
{
  assert(message->base.descriptor == &proto__token_get_info_query__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__token_get_info_query__pack
                     (const Proto__TokenGetInfoQuery *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__token_get_info_query__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__token_get_info_query__pack_to_buffer
                     (const Proto__TokenGetInfoQuery *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__token_get_info_query__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__TokenGetInfoQuery *
       proto__token_get_info_query__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__TokenGetInfoQuery *)
     protobuf_c_message_unpack (&proto__token_get_info_query__descriptor,
                                allocator, len, data);
}
void   proto__token_get_info_query__free_unpacked
                     (Proto__TokenGetInfoQuery *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__token_get_info_query__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__token_info__init
                     (Proto__TokenInfo         *message)
{
  static const Proto__TokenInfo init_value = PROTO__TOKEN_INFO__INIT;
  *message = init_value;
}
size_t proto__token_info__get_packed_size
                     (const Proto__TokenInfo *message)
{
  assert(message->base.descriptor == &proto__token_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__token_info__pack
                     (const Proto__TokenInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__token_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__token_info__pack_to_buffer
                     (const Proto__TokenInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__token_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__TokenInfo *
       proto__token_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__TokenInfo *)
     protobuf_c_message_unpack (&proto__token_info__descriptor,
                                allocator, len, data);
}
void   proto__token_info__free_unpacked
                     (Proto__TokenInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__token_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__token_get_info_response__init
                     (Proto__TokenGetInfoResponse         *message)
{
  static const Proto__TokenGetInfoResponse init_value = PROTO__TOKEN_GET_INFO_RESPONSE__INIT;
  *message = init_value;
}
size_t proto__token_get_info_response__get_packed_size
                     (const Proto__TokenGetInfoResponse *message)
{
  assert(message->base.descriptor == &proto__token_get_info_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__token_get_info_response__pack
                     (const Proto__TokenGetInfoResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__token_get_info_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__token_get_info_response__pack_to_buffer
                     (const Proto__TokenGetInfoResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__token_get_info_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__TokenGetInfoResponse *
       proto__token_get_info_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__TokenGetInfoResponse *)
     protobuf_c_message_unpack (&proto__token_get_info_response__descriptor,
                                allocator, len, data);
}
void   proto__token_get_info_response__free_unpacked
                     (Proto__TokenGetInfoResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__token_get_info_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor proto__token_get_info_query__field_descriptors[2] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenGetInfoQuery, header),
    &proto__query_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "token",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenGetInfoQuery, token),
    &proto__token_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__token_get_info_query__field_indices_by_name[] = {
  0,   /* field[0] = header */
  1,   /* field[1] = token */
};
static const ProtobufCIntRange proto__token_get_info_query__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto__token_get_info_query__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.TokenGetInfoQuery",
  "TokenGetInfoQuery",
  "Proto__TokenGetInfoQuery",
  "proto",
  sizeof(Proto__TokenGetInfoQuery),
  2,
  proto__token_get_info_query__field_descriptors,
  proto__token_get_info_query__field_indices_by_name,
  1,  proto__token_get_info_query__number_ranges,
  (ProtobufCMessageInit) proto__token_get_info_query__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__token_info__field_descriptors[23] =
{
  {
    "tokenId",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenInfo, tokenid),
    &proto__token_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenInfo, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "symbol",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenInfo, symbol),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "decimals",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenInfo, decimals),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "totalSupply",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenInfo, totalsupply),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "treasury",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenInfo, treasury),
    &proto__account_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "adminKey",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenInfo, adminkey),
    &proto__key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kycKey",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenInfo, kyckey),
    &proto__key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "freezeKey",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenInfo, freezekey),
    &proto__key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wipeKey",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenInfo, wipekey),
    &proto__key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "supplyKey",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenInfo, supplykey),
    &proto__key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "defaultFreezeStatus",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenInfo, defaultfreezestatus),
    &proto__token_freeze_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "defaultKycStatus",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenInfo, defaultkycstatus),
    &proto__token_kyc_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deleted",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenInfo, deleted),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "autoRenewAccount",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenInfo, autorenewaccount),
    &proto__account_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "autoRenewPeriod",
    16,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenInfo, autorenewperiod),
    &proto__duration__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "expiry",
    17,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenInfo, expiry),
    &proto__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "memo",
    18,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenInfo, memo),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tokenType",
    19,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenInfo, tokentype),
    &proto__token_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "supplyType",
    20,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenInfo, supplytype),
    &proto__token_supply_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maxSupply",
    21,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenInfo, maxsupply),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fee_schedule_key",
    22,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenInfo, fee_schedule_key),
    &proto__key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "custom_fees",
    23,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Proto__TokenInfo, n_custom_fees),
    offsetof(Proto__TokenInfo, custom_fees),
    &proto__custom_fee__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__token_info__field_indices_by_name[] = {
  6,   /* field[6] = adminKey */
  14,   /* field[14] = autoRenewAccount */
  15,   /* field[15] = autoRenewPeriod */
  22,   /* field[22] = custom_fees */
  3,   /* field[3] = decimals */
  11,   /* field[11] = defaultFreezeStatus */
  12,   /* field[12] = defaultKycStatus */
  13,   /* field[13] = deleted */
  16,   /* field[16] = expiry */
  21,   /* field[21] = fee_schedule_key */
  8,   /* field[8] = freezeKey */
  7,   /* field[7] = kycKey */
  20,   /* field[20] = maxSupply */
  17,   /* field[17] = memo */
  1,   /* field[1] = name */
  10,   /* field[10] = supplyKey */
  19,   /* field[19] = supplyType */
  2,   /* field[2] = symbol */
  0,   /* field[0] = tokenId */
  18,   /* field[18] = tokenType */
  4,   /* field[4] = totalSupply */
  5,   /* field[5] = treasury */
  9,   /* field[9] = wipeKey */
};
static const ProtobufCIntRange proto__token_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 23 }
};
const ProtobufCMessageDescriptor proto__token_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.TokenInfo",
  "TokenInfo",
  "Proto__TokenInfo",
  "proto",
  sizeof(Proto__TokenInfo),
  23,
  proto__token_info__field_descriptors,
  proto__token_info__field_indices_by_name,
  1,  proto__token_info__number_ranges,
  (ProtobufCMessageInit) proto__token_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__token_get_info_response__field_descriptors[2] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenGetInfoResponse, header),
    &proto__response_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tokenInfo",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenGetInfoResponse, tokeninfo),
    &proto__token_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__token_get_info_response__field_indices_by_name[] = {
  0,   /* field[0] = header */
  1,   /* field[1] = tokenInfo */
};
static const ProtobufCIntRange proto__token_get_info_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto__token_get_info_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.TokenGetInfoResponse",
  "TokenGetInfoResponse",
  "Proto__TokenGetInfoResponse",
  "proto",
  sizeof(Proto__TokenGetInfoResponse),
  2,
  proto__token_get_info_response__field_descriptors,
  proto__token_get_info_response__field_indices_by_name,
  1,  proto__token_get_info_response__number_ranges,
  (ProtobufCMessageInit) proto__token_get_info_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
