/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: TokenUpdate.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "TokenUpdate.pb-c.h"
void   proto__token_update_transaction_body__init
                     (Proto__TokenUpdateTransactionBody         *message)
{
  static const Proto__TokenUpdateTransactionBody init_value = PROTO__TOKEN_UPDATE_TRANSACTION_BODY__INIT;
  *message = init_value;
}
size_t proto__token_update_transaction_body__get_packed_size
                     (const Proto__TokenUpdateTransactionBody *message)
{
  assert(message->base.descriptor == &proto__token_update_transaction_body__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__token_update_transaction_body__pack
                     (const Proto__TokenUpdateTransactionBody *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__token_update_transaction_body__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__token_update_transaction_body__pack_to_buffer
                     (const Proto__TokenUpdateTransactionBody *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__token_update_transaction_body__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__TokenUpdateTransactionBody *
       proto__token_update_transaction_body__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__TokenUpdateTransactionBody *)
     protobuf_c_message_unpack (&proto__token_update_transaction_body__descriptor,
                                allocator, len, data);
}
void   proto__token_update_transaction_body__free_unpacked
                     (Proto__TokenUpdateTransactionBody *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__token_update_transaction_body__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor proto__token_update_transaction_body__field_descriptors[14] =
{
  {
    "token",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenUpdateTransactionBody, token),
    &proto__token_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "symbol",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenUpdateTransactionBody, symbol),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenUpdateTransactionBody, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "treasury",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenUpdateTransactionBody, treasury),
    &proto__account_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "adminKey",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenUpdateTransactionBody, adminkey),
    &proto__key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kycKey",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenUpdateTransactionBody, kyckey),
    &proto__key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "freezeKey",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenUpdateTransactionBody, freezekey),
    &proto__key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wipeKey",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenUpdateTransactionBody, wipekey),
    &proto__key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "supplyKey",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenUpdateTransactionBody, supplykey),
    &proto__key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "autoRenewAccount",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenUpdateTransactionBody, autorenewaccount),
    &proto__account_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "autoRenewPeriod",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenUpdateTransactionBody, autorenewperiod),
    &proto__duration__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "expiry",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenUpdateTransactionBody, expiry),
    &proto__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "memo",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenUpdateTransactionBody, memo),
    &google__protobuf__string_value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fee_schedule_key",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenUpdateTransactionBody, fee_schedule_key),
    &proto__key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__token_update_transaction_body__field_indices_by_name[] = {
  4,   /* field[4] = adminKey */
  9,   /* field[9] = autoRenewAccount */
  10,   /* field[10] = autoRenewPeriod */
  11,   /* field[11] = expiry */
  13,   /* field[13] = fee_schedule_key */
  6,   /* field[6] = freezeKey */
  5,   /* field[5] = kycKey */
  12,   /* field[12] = memo */
  2,   /* field[2] = name */
  8,   /* field[8] = supplyKey */
  1,   /* field[1] = symbol */
  0,   /* field[0] = token */
  3,   /* field[3] = treasury */
  7,   /* field[7] = wipeKey */
};
static const ProtobufCIntRange proto__token_update_transaction_body__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 14 }
};
const ProtobufCMessageDescriptor proto__token_update_transaction_body__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.TokenUpdateTransactionBody",
  "TokenUpdateTransactionBody",
  "Proto__TokenUpdateTransactionBody",
  "proto",
  sizeof(Proto__TokenUpdateTransactionBody),
  14,
  proto__token_update_transaction_body__field_descriptors,
  proto__token_update_transaction_body__field_indices_by_name,
  1,  proto__token_update_transaction_body__number_ranges,
  (ProtobufCMessageInit) proto__token_update_transaction_body__init,
  NULL,NULL,NULL    /* reserved[123] */
};
