/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: TokenUnfreezeAccount.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "TokenUnfreezeAccount.pb-c.h"
void   proto__token_unfreeze_account_transaction_body__init
                     (Proto__TokenUnfreezeAccountTransactionBody         *message)
{
  static const Proto__TokenUnfreezeAccountTransactionBody init_value = PROTO__TOKEN_UNFREEZE_ACCOUNT_TRANSACTION_BODY__INIT;
  *message = init_value;
}
size_t proto__token_unfreeze_account_transaction_body__get_packed_size
                     (const Proto__TokenUnfreezeAccountTransactionBody *message)
{
  assert(message->base.descriptor == &proto__token_unfreeze_account_transaction_body__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__token_unfreeze_account_transaction_body__pack
                     (const Proto__TokenUnfreezeAccountTransactionBody *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__token_unfreeze_account_transaction_body__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__token_unfreeze_account_transaction_body__pack_to_buffer
                     (const Proto__TokenUnfreezeAccountTransactionBody *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__token_unfreeze_account_transaction_body__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__TokenUnfreezeAccountTransactionBody *
       proto__token_unfreeze_account_transaction_body__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__TokenUnfreezeAccountTransactionBody *)
     protobuf_c_message_unpack (&proto__token_unfreeze_account_transaction_body__descriptor,
                                allocator, len, data);
}
void   proto__token_unfreeze_account_transaction_body__free_unpacked
                     (Proto__TokenUnfreezeAccountTransactionBody *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__token_unfreeze_account_transaction_body__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor proto__token_unfreeze_account_transaction_body__field_descriptors[2] =
{
  {
    "token",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenUnfreezeAccountTransactionBody, token),
    &proto__token_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "account",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenUnfreezeAccountTransactionBody, account),
    &proto__account_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__token_unfreeze_account_transaction_body__field_indices_by_name[] = {
  1,   /* field[1] = account */
  0,   /* field[0] = token */
};
static const ProtobufCIntRange proto__token_unfreeze_account_transaction_body__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto__token_unfreeze_account_transaction_body__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.TokenUnfreezeAccountTransactionBody",
  "TokenUnfreezeAccountTransactionBody",
  "Proto__TokenUnfreezeAccountTransactionBody",
  "proto",
  sizeof(Proto__TokenUnfreezeAccountTransactionBody),
  2,
  proto__token_unfreeze_account_transaction_body__field_descriptors,
  proto__token_unfreeze_account_transaction_body__field_indices_by_name,
  1,  proto__token_unfreeze_account_transaction_body__number_ranges,
  (ProtobufCMessageInit) proto__token_unfreeze_account_transaction_body__init,
  NULL,NULL,NULL    /* reserved[123] */
};
