/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: TokenGetAccountNftInfos.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "TokenGetAccountNftInfos.pb-c.h"
void   proto__token_get_account_nft_infos_query__init
                     (Proto__TokenGetAccountNftInfosQuery         *message)
{
  static const Proto__TokenGetAccountNftInfosQuery init_value = PROTO__TOKEN_GET_ACCOUNT_NFT_INFOS_QUERY__INIT;
  *message = init_value;
}
size_t proto__token_get_account_nft_infos_query__get_packed_size
                     (const Proto__TokenGetAccountNftInfosQuery *message)
{
  assert(message->base.descriptor == &proto__token_get_account_nft_infos_query__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__token_get_account_nft_infos_query__pack
                     (const Proto__TokenGetAccountNftInfosQuery *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__token_get_account_nft_infos_query__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__token_get_account_nft_infos_query__pack_to_buffer
                     (const Proto__TokenGetAccountNftInfosQuery *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__token_get_account_nft_infos_query__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__TokenGetAccountNftInfosQuery *
       proto__token_get_account_nft_infos_query__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__TokenGetAccountNftInfosQuery *)
     protobuf_c_message_unpack (&proto__token_get_account_nft_infos_query__descriptor,
                                allocator, len, data);
}
void   proto__token_get_account_nft_infos_query__free_unpacked
                     (Proto__TokenGetAccountNftInfosQuery *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__token_get_account_nft_infos_query__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto__token_get_account_nft_infos_response__init
                     (Proto__TokenGetAccountNftInfosResponse         *message)
{
  static const Proto__TokenGetAccountNftInfosResponse init_value = PROTO__TOKEN_GET_ACCOUNT_NFT_INFOS_RESPONSE__INIT;
  *message = init_value;
}
size_t proto__token_get_account_nft_infos_response__get_packed_size
                     (const Proto__TokenGetAccountNftInfosResponse *message)
{
  assert(message->base.descriptor == &proto__token_get_account_nft_infos_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__token_get_account_nft_infos_response__pack
                     (const Proto__TokenGetAccountNftInfosResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__token_get_account_nft_infos_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__token_get_account_nft_infos_response__pack_to_buffer
                     (const Proto__TokenGetAccountNftInfosResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__token_get_account_nft_infos_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__TokenGetAccountNftInfosResponse *
       proto__token_get_account_nft_infos_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__TokenGetAccountNftInfosResponse *)
     protobuf_c_message_unpack (&proto__token_get_account_nft_infos_response__descriptor,
                                allocator, len, data);
}
void   proto__token_get_account_nft_infos_response__free_unpacked
                     (Proto__TokenGetAccountNftInfosResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__token_get_account_nft_infos_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor proto__token_get_account_nft_infos_query__field_descriptors[4] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenGetAccountNftInfosQuery, header),
    &proto__query_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "accountID",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenGetAccountNftInfosQuery, accountid),
    &proto__account_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenGetAccountNftInfosQuery, start),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenGetAccountNftInfosQuery, end),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__token_get_account_nft_infos_query__field_indices_by_name[] = {
  1,   /* field[1] = accountID */
  3,   /* field[3] = end */
  0,   /* field[0] = header */
  2,   /* field[2] = start */
};
static const ProtobufCIntRange proto__token_get_account_nft_infos_query__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor proto__token_get_account_nft_infos_query__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.TokenGetAccountNftInfosQuery",
  "TokenGetAccountNftInfosQuery",
  "Proto__TokenGetAccountNftInfosQuery",
  "proto",
  sizeof(Proto__TokenGetAccountNftInfosQuery),
  4,
  proto__token_get_account_nft_infos_query__field_descriptors,
  proto__token_get_account_nft_infos_query__field_indices_by_name,
  1,  proto__token_get_account_nft_infos_query__number_ranges,
  (ProtobufCMessageInit) proto__token_get_account_nft_infos_query__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto__token_get_account_nft_infos_response__field_descriptors[2] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Proto__TokenGetAccountNftInfosResponse, header),
    &proto__response_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nfts",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Proto__TokenGetAccountNftInfosResponse, n_nfts),
    offsetof(Proto__TokenGetAccountNftInfosResponse, nfts),
    &proto__token_nft_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__token_get_account_nft_infos_response__field_indices_by_name[] = {
  0,   /* field[0] = header */
  1,   /* field[1] = nfts */
};
static const ProtobufCIntRange proto__token_get_account_nft_infos_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto__token_get_account_nft_infos_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.TokenGetAccountNftInfosResponse",
  "TokenGetAccountNftInfosResponse",
  "Proto__TokenGetAccountNftInfosResponse",
  "proto",
  sizeof(Proto__TokenGetAccountNftInfosResponse),
  2,
  proto__token_get_account_nft_infos_response__field_descriptors,
  proto__token_get_account_nft_infos_response__field_indices_by_name,
  1,  proto__token_get_account_nft_infos_response__number_ranges,
  (ProtobufCMessageInit) proto__token_get_account_nft_infos_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
