/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: TokenWipeAccount.proto */

#ifndef PROTOBUF_C_TokenWipeAccount_2eproto__INCLUDED
#define PROTOBUF_C_TokenWipeAccount_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "BasicTypes.pb-c.h"

typedef struct Proto__TokenWipeAccountTransactionBody Proto__TokenWipeAccountTransactionBody;


/* --- enums --- */


/* --- messages --- */

/*
 * Wipes the provided amount of tokens from the specified Account. Must be signed by the Token's Wipe key.
 *If the provided account is not found, the transaction will resolve to INVALID_ACCOUNT_ID.
 *If the provided account has been deleted, the transaction will resolve to ACCOUNT_DELETED.
 *If the provided token is not found, the transaction will resolve to INVALID_TOKEN_ID.
 *If the provided token has been deleted, the transaction will resolve to TOKEN_WAS_DELETED.
 *If an Association between the provided token and account is not found, the transaction will resolve to TOKEN_NOT_ASSOCIATED_TO_ACCOUNT.
 *If Wipe Key is not present in the Token, transaction results in TOKEN_HAS_NO_WIPE_KEY.
 *If the provided account is the Token's Treasury Account, transaction results in CANNOT_WIPE_TOKEN_TREASURY_ACCOUNT
 *On success, tokens are removed from the account and the total supply of the token is decreased by the wiped amount.
 *If both amount and serialNumbers get filled, a INVALID_TRANSACTION_BODY response code will be returned.
 *If neither the amount nor the serialNumbers get filled, a INVALID_WIPING_AMOUNT response code will be returned.
 *If the serialNumbers list contains a non-positive integer as a serial number, a INVALID_NFT_ID response code will be returned.
 *If the serialNumbers' list count is greater than the batch size limit global dynamic property, a BATCH_SIZE_LIMIT_EXCEEDED response code will be returned.
 *The amount provided is in the lowest denomination possible. Example:
 *Token A has 2 decimals. In order to wipe 100 tokens from account, one must provide amount of 10000. In order to wipe 100.55 tokens, one must provide amount of 10055.
 */
struct  Proto__TokenWipeAccountTransactionBody
{
  ProtobufCMessage base;
  /*
   * The token for which the account will be wiped. If token does not exist, transaction results in INVALID_TOKEN_ID
   */
  Proto__TokenID *token;
  /*
   * The account to be wiped
   */
  Proto__AccountID *account;
  /*
   * Applicable to tokens of type FUNGIBLE_COMMON. The amount of tokens to wipe from the specified account. Amount must be a positive non-zero number in the lowest denomination possible, not bigger than the token balance of the account (0; balance]
   */
  uint64_t amount;
  /*
   * Applicable to tokens of type NON_FUNGIBLE_UNIQUE. The list of serial numbers to be wiped.
   */
  size_t n_serialnumbers;
  int64_t *serialnumbers;
};
#define PROTO__TOKEN_WIPE_ACCOUNT_TRANSACTION_BODY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__token_wipe_account_transaction_body__descriptor) \
    , NULL, NULL, 0, 0,NULL }


/* Proto__TokenWipeAccountTransactionBody methods */
void   proto__token_wipe_account_transaction_body__init
                     (Proto__TokenWipeAccountTransactionBody         *message);
size_t proto__token_wipe_account_transaction_body__get_packed_size
                     (const Proto__TokenWipeAccountTransactionBody   *message);
size_t proto__token_wipe_account_transaction_body__pack
                     (const Proto__TokenWipeAccountTransactionBody   *message,
                      uint8_t             *out);
size_t proto__token_wipe_account_transaction_body__pack_to_buffer
                     (const Proto__TokenWipeAccountTransactionBody   *message,
                      ProtobufCBuffer     *buffer);
Proto__TokenWipeAccountTransactionBody *
       proto__token_wipe_account_transaction_body__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__token_wipe_account_transaction_body__free_unpacked
                     (Proto__TokenWipeAccountTransactionBody *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Proto__TokenWipeAccountTransactionBody_Closure)
                 (const Proto__TokenWipeAccountTransactionBody *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor proto__token_wipe_account_transaction_body__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_TokenWipeAccount_2eproto__INCLUDED */
