/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: TransactionContents.proto */

#ifndef PROTOBUF_C_TransactionContents_2eproto__INCLUDED
#define PROTOBUF_C_TransactionContents_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "BasicTypes.pb-c.h"

typedef struct Proto__SignedTransaction Proto__SignedTransaction;


/* --- enums --- */


/* --- messages --- */

struct  Proto__SignedTransaction
{
  ProtobufCMessage base;
  /*
   * TransactionBody serialized into bytes, which needs to be signed
   */
  ProtobufCBinaryData bodybytes;
  /*
   * The signatures on the body with the new format, to authorize the transaction
   */
  Proto__SignatureMap *sigmap;
};
#define PROTO__SIGNED_TRANSACTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__signed_transaction__descriptor) \
    , {0,NULL}, NULL }


/* Proto__SignedTransaction methods */
void   proto__signed_transaction__init
                     (Proto__SignedTransaction         *message);
size_t proto__signed_transaction__get_packed_size
                     (const Proto__SignedTransaction   *message);
size_t proto__signed_transaction__pack
                     (const Proto__SignedTransaction   *message,
                      uint8_t             *out);
size_t proto__signed_transaction__pack_to_buffer
                     (const Proto__SignedTransaction   *message,
                      ProtobufCBuffer     *buffer);
Proto__SignedTransaction *
       proto__signed_transaction__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__signed_transaction__free_unpacked
                     (Proto__SignedTransaction *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Proto__SignedTransaction_Closure)
                 (const Proto__SignedTransaction *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor proto__signed_transaction__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_TransactionContents_2eproto__INCLUDED */
