/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: UncheckedSubmit.proto */

#ifndef PROTOBUF_C_UncheckedSubmit_2eproto__INCLUDED
#define PROTOBUF_C_UncheckedSubmit_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Proto__UncheckedSubmitBody Proto__UncheckedSubmitBody;


/* --- enums --- */


/* --- messages --- */

/*
 *Submit an arbitrary (serialized) Transaction to the network without prechecks. Requires superuser privileges.
 */
struct  Proto__UncheckedSubmitBody
{
  ProtobufCMessage base;
  /*
   * The serialized bytes of the Transaction to be submitted without prechecks
   */
  ProtobufCBinaryData transactionbytes;
};
#define PROTO__UNCHECKED_SUBMIT_BODY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto__unchecked_submit_body__descriptor) \
    , {0,NULL} }


/* Proto__UncheckedSubmitBody methods */
void   proto__unchecked_submit_body__init
                     (Proto__UncheckedSubmitBody         *message);
size_t proto__unchecked_submit_body__get_packed_size
                     (const Proto__UncheckedSubmitBody   *message);
size_t proto__unchecked_submit_body__pack
                     (const Proto__UncheckedSubmitBody   *message,
                      uint8_t             *out);
size_t proto__unchecked_submit_body__pack_to_buffer
                     (const Proto__UncheckedSubmitBody   *message,
                      ProtobufCBuffer     *buffer);
Proto__UncheckedSubmitBody *
       proto__unchecked_submit_body__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto__unchecked_submit_body__free_unpacked
                     (Proto__UncheckedSubmitBody *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Proto__UncheckedSubmitBody_Closure)
                 (const Proto__UncheckedSubmitBody *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor proto__unchecked_submit_body__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_UncheckedSubmit_2eproto__INCLUDED */
